// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package goverter

import (
	uuid "github.com/gofrs/uuid"
	db "github.com/stashapp/stash-box/internal/db"
	models "github.com/stashapp/stash-box/pkg/models"
	"time"
)

type CreateParamsConverterImpl struct{}

func (c *CreateParamsConverterImpl) ConvertEditToCreateParams(source models.Edit) db.CreateEditParams {
	var dbCreateEditParams db.CreateEditParams
	dbCreateEditParams.ID = c.uuidUUIDToUuidUUID(source.ID)
	dbCreateEditParams.UserID = ConvertUUIDNullToNullUUID(source.UserID)
	dbCreateEditParams.TargetType = source.TargetType
	dbCreateEditParams.Operation = source.Operation
	dbCreateEditParams.Data = ConvertJSONToBytes(source.Data)
	dbCreateEditParams.Votes = source.VoteCount
	dbCreateEditParams.Status = source.Status
	dbCreateEditParams.Applied = source.Applied
	dbCreateEditParams.CreatedAt = ConvertTime(source.CreatedAt)
	dbCreateEditParams.UpdatedAt = c.pTimeTimeToPTimeTime(source.UpdatedAt)
	return dbCreateEditParams
}
func (c *CreateParamsConverterImpl) ConvertEditVoteToCreateParams(source models.EditVote) db.CreateEditVoteParams {
	var dbCreateEditVoteParams db.CreateEditVoteParams
	dbCreateEditVoteParams.EditID = c.uuidUUIDToUuidUUID(source.EditID)
	dbCreateEditVoteParams.UserID = ConvertNullUUIDToUUID(source.UserID)
	dbCreateEditVoteParams.Vote = source.Vote
	return dbCreateEditVoteParams
}
func (c *CreateParamsConverterImpl) ConvertPerformerToCreateParams(source models.Performer) db.CreatePerformerParams {
	var dbCreatePerformerParams db.CreatePerformerParams
	dbCreatePerformerParams.ID = c.uuidUUIDToUuidUUID(source.ID)
	dbCreatePerformerParams.Name = source.Name
	if source.Disambiguation != nil {
		xstring := *source.Disambiguation
		dbCreatePerformerParams.Disambiguation = &xstring
	}
	if source.Gender != nil {
		modelsGenderEnum := c.modelsGenderEnumToModelsGenderEnum(*source.Gender)
		dbCreatePerformerParams.Gender = &modelsGenderEnum
	}
	if source.BirthDate != nil {
		xstring2 := *source.BirthDate
		dbCreatePerformerParams.Birthdate = &xstring2
	}
	dbCreatePerformerParams.Ethnicity = ConvertEthnicityEnumToPgText(source.Ethnicity)
	if source.Country != nil {
		xstring3 := *source.Country
		dbCreatePerformerParams.Country = &xstring3
	}
	dbCreatePerformerParams.EyeColor = ConvertEyeColorEnumToPgText(source.EyeColor)
	dbCreatePerformerParams.HairColor = ConvertHairColorEnumToPgText(source.HairColor)
	if source.Height != nil {
		xint := *source.Height
		dbCreatePerformerParams.Height = &xint
	}
	if source.CupSize != nil {
		xstring4 := *source.CupSize
		dbCreatePerformerParams.CupSize = &xstring4
	}
	if source.BandSize != nil {
		xint2 := *source.BandSize
		dbCreatePerformerParams.BandSize = &xint2
	}
	if source.HipSize != nil {
		xint3 := *source.HipSize
		dbCreatePerformerParams.HipSize = &xint3
	}
	if source.WaistSize != nil {
		xint4 := *source.WaistSize
		dbCreatePerformerParams.WaistSize = &xint4
	}
	dbCreatePerformerParams.BreastType = ConvertBreastTypeEnumToPgText(source.BreastType)
	if source.CareerStartYear != nil {
		xint5 := *source.CareerStartYear
		dbCreatePerformerParams.CareerStartYear = &xint5
	}
	if source.CareerEndYear != nil {
		xint6 := *source.CareerEndYear
		dbCreatePerformerParams.CareerEndYear = &xint6
	}
	dbCreatePerformerParams.CreatedAt = ConvertTime(source.Created)
	dbCreatePerformerParams.UpdatedAt = ConvertTime(source.Updated)
	dbCreatePerformerParams.Deleted = source.Deleted
	if source.DeathDate != nil {
		xstring5 := *source.DeathDate
		dbCreatePerformerParams.Deathdate = &xstring5
	}
	return dbCreatePerformerParams
}
func (c *CreateParamsConverterImpl) ConvertSceneToCreateParams(source models.Scene) db.CreateSceneParams {
	var dbCreateSceneParams db.CreateSceneParams
	dbCreateSceneParams.ID = c.uuidUUIDToUuidUUID(source.ID)
	if source.Title != nil {
		xstring := *source.Title
		dbCreateSceneParams.Title = &xstring
	}
	if source.Details != nil {
		xstring2 := *source.Details
		dbCreateSceneParams.Details = &xstring2
	}
	if source.Date != nil {
		xstring3 := *source.Date
		dbCreateSceneParams.Date = &xstring3
	}
	if source.ProductionDate != nil {
		xstring4 := *source.ProductionDate
		dbCreateSceneParams.ProductionDate = &xstring4
	}
	dbCreateSceneParams.StudioID = ConvertUUIDNullToNullUUID(source.StudioID)
	dbCreateSceneParams.CreatedAt = ConvertTime(source.CreatedAt)
	dbCreateSceneParams.UpdatedAt = ConvertTime(source.UpdatedAt)
	if source.Duration != nil {
		xint := *source.Duration
		dbCreateSceneParams.Duration = &xint
	}
	if source.Director != nil {
		xstring5 := *source.Director
		dbCreateSceneParams.Director = &xstring5
	}
	if source.Code != nil {
		xstring6 := *source.Code
		dbCreateSceneParams.Code = &xstring6
	}
	dbCreateSceneParams.Deleted = source.Deleted
	return dbCreateSceneParams
}
func (c *CreateParamsConverterImpl) ConvertSiteToCreateParams(source models.Site) db.CreateSiteParams {
	var dbCreateSiteParams db.CreateSiteParams
	dbCreateSiteParams.ID = c.uuidUUIDToUuidUUID(source.ID)
	dbCreateSiteParams.Name = source.Name
	if source.Description != nil {
		xstring := *source.Description
		dbCreateSiteParams.Description = &xstring
	}
	if source.URL != nil {
		xstring2 := *source.URL
		dbCreateSiteParams.Url = &xstring2
	}
	if source.Regex != nil {
		xstring3 := *source.Regex
		dbCreateSiteParams.Regex = &xstring3
	}
	if source.ValidTypes != nil {
		dbCreateSiteParams.ValidTypes = make([]string, len(source.ValidTypes))
		for i := 0; i < len(source.ValidTypes); i++ {
			dbCreateSiteParams.ValidTypes[i] = source.ValidTypes[i]
		}
	}
	dbCreateSiteParams.CreatedAt = ConvertTime(source.CreatedAt)
	dbCreateSiteParams.UpdatedAt = ConvertTime(source.UpdatedAt)
	return dbCreateSiteParams
}
func (c *CreateParamsConverterImpl) ConvertStudioToCreateParams(source models.Studio) db.CreateStudioParams {
	var dbCreateStudioParams db.CreateStudioParams
	dbCreateStudioParams.ID = c.uuidUUIDToUuidUUID(source.ID)
	dbCreateStudioParams.Name = source.Name
	dbCreateStudioParams.ParentStudioID = ConvertUUIDNullToNullUUID(source.ParentStudioID)
	dbCreateStudioParams.CreatedAt = ConvertTime(source.CreatedAt)
	dbCreateStudioParams.UpdatedAt = ConvertTime(source.UpdatedAt)
	dbCreateStudioParams.Deleted = source.Deleted
	return dbCreateStudioParams
}
func (c *CreateParamsConverterImpl) ConvertTagToCreateParams(source models.Tag) db.CreateTagParams {
	var dbCreateTagParams db.CreateTagParams
	dbCreateTagParams.ID = c.uuidUUIDToUuidUUID(source.ID)
	dbCreateTagParams.Name = source.Name
	dbCreateTagParams.CategoryID = ConvertUUIDNullToNullUUID(source.CategoryID)
	if source.Description != nil {
		xstring := *source.Description
		dbCreateTagParams.Description = &xstring
	}
	dbCreateTagParams.CreatedAt = ConvertTime(source.Created)
	dbCreateTagParams.UpdatedAt = ConvertTime(source.Updated)
	dbCreateTagParams.Deleted = source.Deleted
	return dbCreateTagParams
}
func (c *CreateParamsConverterImpl) modelsGenderEnumToModelsGenderEnum(source models.GenderEnum) models.GenderEnum {
	var modelsGenderEnum models.GenderEnum
	switch source {
	case models.GenderEnumFemale:
		modelsGenderEnum = models.GenderEnumFemale
	case models.GenderEnumIntersex:
		modelsGenderEnum = models.GenderEnumIntersex
	case models.GenderEnumMale:
		modelsGenderEnum = models.GenderEnumMale
	case models.GenderEnumNonBinary:
		modelsGenderEnum = models.GenderEnumNonBinary
	case models.GenderEnumTransgenderFemale:
		modelsGenderEnum = models.GenderEnumTransgenderFemale
	case models.GenderEnumTransgenderMale:
		modelsGenderEnum = models.GenderEnumTransgenderMale
	default: // ignored
	}
	return modelsGenderEnum
}
func (c *CreateParamsConverterImpl) pTimeTimeToPTimeTime(source *time.Time) *time.Time {
	var pTimeTime *time.Time
	if source != nil {
		timeTime := ConvertTime((*source))
		pTimeTime = &timeTime
	}
	return pTimeTime
}
func (c *CreateParamsConverterImpl) uuidUUIDToUuidUUID(source uuid.UUID) uuid.UUID {
	var uuidUUID uuid.UUID
	for i := 0; i < len(source); i++ {
		uuidUUID[i] = source[i]
	}
	return uuidUUID
}

type InputConverterImpl struct{}

func (c *InputConverterImpl) ConvertSceneDraftInput(source models.SceneDraftInput) models.SceneDraft {
	var modelsSceneDraft models.SceneDraft
	modelsSceneDraft.ID = c.pUuidUUIDToPUuidUUID(source.ID)
	if source.Title != nil {
		xstring := *source.Title
		modelsSceneDraft.Title = &xstring
	}
	if source.Code != nil {
		xstring2 := *source.Code
		modelsSceneDraft.Code = &xstring2
	}
	if source.Details != nil {
		xstring3 := *source.Details
		modelsSceneDraft.Details = &xstring3
	}
	if source.Director != nil {
		xstring4 := *source.Director
		modelsSceneDraft.Director = &xstring4
	}
	if source.Urls != nil {
		modelsSceneDraft.URLs = make([]string, len(source.Urls))
		for i := 0; i < len(source.Urls); i++ {
			modelsSceneDraft.URLs[i] = source.Urls[i]
		}
	}
	if source.Date != nil {
		xstring5 := *source.Date
		modelsSceneDraft.Date = &xstring5
	}
	if source.ProductionDate != nil {
		xstring6 := *source.ProductionDate
		modelsSceneDraft.ProductionDate = &xstring6
	}
	modelsSceneDraft.Studio = ConvertDraftEntityInputPtr(source.Studio)
	modelsSceneDraft.Performers = ConvertDraftEntityInputSlice(source.Performers)
	modelsSceneDraft.Fingerprints = FilterDraftFingerprints(source.Fingerprints)
	return modelsSceneDraft
}
func (c *InputConverterImpl) ConvertURLInputToURL(source models.URLInput) models.URL {
	var modelsURL models.URL
	modelsURL.URL = source.URL
	modelsURL.SiteID = c.uuidUUIDToUuidUUID2(source.SiteID)
	return modelsURL
}
func (c *InputConverterImpl) pUuidUUIDToPUuidUUID(source *uuid.UUID) *uuid.UUID {
	var pUuidUUID *uuid.UUID
	if source != nil {
		uuidUUID := c.uuidUUIDToUuidUUID2((*source))
		pUuidUUID = &uuidUUID
	}
	return pUuidUUID
}
func (c *InputConverterImpl) uuidUUIDToUuidUUID2(source uuid.UUID) uuid.UUID {
	var uuidUUID uuid.UUID
	for i := 0; i < len(source); i++ {
		uuidUUID[i] = source[i]
	}
	return uuidUUID
}

type ModelConverterImpl struct{}

func (c *ModelConverterImpl) ConvertEdit(source db.Edit) *models.Edit {
	var modelsEdit models.Edit
	modelsEdit.ID = c.uuidUUIDToUuidUUID3(source.ID)
	modelsEdit.UserID = c.uuidNullUUIDToUuidNullUUID(source.UserID)
	modelsEdit.TargetType = source.TargetType
	modelsEdit.Operation = source.Operation
	modelsEdit.VoteCount = source.Votes
	modelsEdit.Status = source.Status
	modelsEdit.Applied = source.Applied
	modelsEdit.Data = ConvertBytesToJSON(source.Data)
	modelsEdit.Bot = source.Bot
	modelsEdit.CreatedAt = ConvertTime(source.CreatedAt)
	modelsEdit.UpdateCount = source.UpdateCount
	modelsEdit.UpdatedAt = c.pTimeTimeToPTimeTime2(source.UpdatedAt)
	modelsEdit.ClosedAt = c.pTimeTimeToPTimeTime2(source.ClosedAt)
	return &modelsEdit
}
func (c *ModelConverterImpl) ConvertEditComment(source db.EditComment) *models.EditComment {
	var modelsEditComment models.EditComment
	modelsEditComment.ID = c.uuidUUIDToUuidUUID3(source.ID)
	modelsEditComment.EditID = c.uuidUUIDToUuidUUID3(source.EditID)
	modelsEditComment.UserID = c.uuidNullUUIDToUuidNullUUID(source.UserID)
	modelsEditComment.CreatedAt = ConvertTime(source.CreatedAt)
	modelsEditComment.Text = source.Text
	return &modelsEditComment
}
func (c *ModelConverterImpl) ConvertEditVote(source db.EditVote) *models.EditVote {
	var modelsEditVote models.EditVote
	modelsEditVote.EditID = c.uuidUUIDToUuidUUID3(source.EditID)
	modelsEditVote.UserID = ConvertUUIDToNullUUID(source.UserID)
	modelsEditVote.CreatedAt = ConvertTime(source.CreatedAt)
	modelsEditVote.Vote = source.Vote
	return &modelsEditVote
}
func (c *ModelConverterImpl) ConvertImage(source db.Image) *models.Image {
	var modelsImage models.Image
	modelsImage.ID = c.uuidUUIDToUuidUUID3(source.ID)
	if source.Url != nil {
		xstring := *source.Url
		modelsImage.RemoteURL = &xstring
	}
	modelsImage.Checksum = source.Checksum
	modelsImage.Width = source.Width
	modelsImage.Height = source.Height
	return &modelsImage
}
func (c *ModelConverterImpl) ConvertPerformer(source db.Performer) *models.Performer {
	var modelsPerformer models.Performer
	modelsPerformer.ID = c.uuidUUIDToUuidUUID3(source.ID)
	modelsPerformer.Name = source.Name
	if source.Disambiguation != nil {
		xstring := *source.Disambiguation
		modelsPerformer.Disambiguation = &xstring
	}
	if source.Gender != nil {
		modelsGenderEnum := c.modelsGenderEnumToModelsGenderEnum2(*source.Gender)
		modelsPerformer.Gender = &modelsGenderEnum
	}
	if source.Birthdate != nil {
		xstring2 := *source.Birthdate
		modelsPerformer.BirthDate = &xstring2
	}
	if source.Deathdate != nil {
		xstring3 := *source.Deathdate
		modelsPerformer.DeathDate = &xstring3
	}
	modelsPerformer.Ethnicity = ConvertTextToEthnicityEnum(source.Ethnicity)
	if source.Country != nil {
		xstring4 := *source.Country
		modelsPerformer.Country = &xstring4
	}
	modelsPerformer.EyeColor = ConvertTextToEyeColorEnum(source.EyeColor)
	modelsPerformer.HairColor = ConvertTextToHairColorEnum(source.HairColor)
	if source.Height != nil {
		xint := *source.Height
		modelsPerformer.Height = &xint
	}
	if source.CupSize != nil {
		xstring5 := *source.CupSize
		modelsPerformer.CupSize = &xstring5
	}
	if source.BandSize != nil {
		xint2 := *source.BandSize
		modelsPerformer.BandSize = &xint2
	}
	if source.WaistSize != nil {
		xint3 := *source.WaistSize
		modelsPerformer.WaistSize = &xint3
	}
	if source.HipSize != nil {
		xint4 := *source.HipSize
		modelsPerformer.HipSize = &xint4
	}
	modelsPerformer.BreastType = ConvertTextToBreastTypeEnum(source.BreastType)
	if source.CareerStartYear != nil {
		xint5 := *source.CareerStartYear
		modelsPerformer.CareerStartYear = &xint5
	}
	if source.CareerEndYear != nil {
		xint6 := *source.CareerEndYear
		modelsPerformer.CareerEndYear = &xint6
	}
	modelsPerformer.Deleted = source.Deleted
	modelsPerformer.Created = ConvertTime(source.CreatedAt)
	modelsPerformer.Updated = ConvertTime(source.UpdatedAt)
	return &modelsPerformer
}
func (c *ModelConverterImpl) ConvertScene(source db.Scene) *models.Scene {
	var modelsScene models.Scene
	modelsScene.ID = c.uuidUUIDToUuidUUID3(source.ID)
	if source.Title != nil {
		xstring := *source.Title
		modelsScene.Title = &xstring
	}
	if source.Details != nil {
		xstring2 := *source.Details
		modelsScene.Details = &xstring2
	}
	if source.Date != nil {
		xstring3 := *source.Date
		modelsScene.Date = &xstring3
	}
	if source.ProductionDate != nil {
		xstring4 := *source.ProductionDate
		modelsScene.ProductionDate = &xstring4
	}
	modelsScene.StudioID = c.uuidNullUUIDToUuidNullUUID(source.StudioID)
	modelsScene.CreatedAt = ConvertTime(source.CreatedAt)
	modelsScene.UpdatedAt = ConvertTime(source.UpdatedAt)
	if source.Duration != nil {
		xint := *source.Duration
		modelsScene.Duration = &xint
	}
	if source.Director != nil {
		xstring5 := *source.Director
		modelsScene.Director = &xstring5
	}
	if source.Code != nil {
		xstring6 := *source.Code
		modelsScene.Code = &xstring6
	}
	modelsScene.Deleted = source.Deleted
	return &modelsScene
}
func (c *ModelConverterImpl) ConvertSite(source db.Site) *models.Site {
	var modelsSite models.Site
	modelsSite.ID = c.uuidUUIDToUuidUUID3(source.ID)
	modelsSite.Name = source.Name
	if source.Description != nil {
		xstring := *source.Description
		modelsSite.Description = &xstring
	}
	if source.Url != nil {
		xstring2 := *source.Url
		modelsSite.URL = &xstring2
	}
	if source.Regex != nil {
		xstring3 := *source.Regex
		modelsSite.Regex = &xstring3
	}
	if source.ValidTypes != nil {
		modelsSite.ValidTypes = make([]string, len(source.ValidTypes))
		for i := 0; i < len(source.ValidTypes); i++ {
			modelsSite.ValidTypes[i] = source.ValidTypes[i]
		}
	}
	modelsSite.CreatedAt = ConvertTime(source.CreatedAt)
	modelsSite.UpdatedAt = ConvertTime(source.UpdatedAt)
	return &modelsSite
}
func (c *ModelConverterImpl) ConvertStudio(source db.Studio) *models.Studio {
	var modelsStudio models.Studio
	modelsStudio.ID = c.uuidUUIDToUuidUUID3(source.ID)
	modelsStudio.Name = source.Name
	modelsStudio.ParentStudioID = c.uuidNullUUIDToUuidNullUUID(source.ParentStudioID)
	modelsStudio.CreatedAt = ConvertTime(source.CreatedAt)
	modelsStudio.UpdatedAt = ConvertTime(source.UpdatedAt)
	modelsStudio.Deleted = source.Deleted
	return &modelsStudio
}
func (c *ModelConverterImpl) ConvertTag(source db.Tag) *models.Tag {
	var modelsTag models.Tag
	modelsTag.ID = c.uuidUUIDToUuidUUID3(source.ID)
	modelsTag.Name = source.Name
	if source.Description != nil {
		xstring := *source.Description
		modelsTag.Description = &xstring
	}
	modelsTag.Deleted = source.Deleted
	modelsTag.CategoryID = c.uuidNullUUIDToUuidNullUUID(source.CategoryID)
	modelsTag.Created = ConvertTime(source.CreatedAt)
	modelsTag.Updated = ConvertTime(source.UpdatedAt)
	return &modelsTag
}
func (c *ModelConverterImpl) ConvertTagCategory(source db.TagCategory) *models.TagCategory {
	var modelsTagCategory models.TagCategory
	modelsTagCategory.ID = c.uuidUUIDToUuidUUID3(source.ID)
	modelsTagCategory.Name = source.Name
	modelsTagCategory.Group = source.Group
	if source.Description != nil {
		xstring := *source.Description
		modelsTagCategory.Description = &xstring
	}
	modelsTagCategory.CreatedAt = ConvertTime(source.CreatedAt)
	modelsTagCategory.UpdatedAt = ConvertTime(source.UpdatedAt)
	return &modelsTagCategory
}
func (c *ModelConverterImpl) ConvertUser(source db.User) *models.User {
	var modelsUser models.User
	modelsUser.ID = c.uuidUUIDToUuidUUID3(source.ID)
	modelsUser.Name = source.Name
	modelsUser.PasswordHash = source.PasswordHash
	modelsUser.Email = source.Email
	modelsUser.APIKey = source.ApiKey
	modelsUser.APICalls = ConvertNullIntToInt(source.ApiCalls)
	modelsUser.InviteTokens = source.InviteTokens
	modelsUser.InvitedByID = c.uuidNullUUIDToUuidNullUUID(source.InvitedBy)
	modelsUser.LastAPICall = ConvertTime(source.LastApiCall)
	modelsUser.CreatedAt = ConvertTime(source.CreatedAt)
	modelsUser.UpdatedAt = ConvertTime(source.UpdatedAt)
	return &modelsUser
}
func (c *ModelConverterImpl) ConvertUserToken(source db.UserToken) *models.UserToken {
	var modelsUserToken models.UserToken
	modelsUserToken.ID = c.uuidUUIDToUuidUUID3(source.ID)
	modelsUserToken.Data = ConvertBytesToJSON(source.Data)
	modelsUserToken.Type = source.Type
	modelsUserToken.CreatedAt = ConvertTime(source.CreatedAt)
	modelsUserToken.ExpiresAt = ConvertTime(source.ExpiresAt)
	return &modelsUserToken
}
func (c *ModelConverterImpl) modelsGenderEnumToModelsGenderEnum2(source models.GenderEnum) models.GenderEnum {
	var modelsGenderEnum models.GenderEnum
	switch source {
	case models.GenderEnumFemale:
		modelsGenderEnum = models.GenderEnumFemale
	case models.GenderEnumIntersex:
		modelsGenderEnum = models.GenderEnumIntersex
	case models.GenderEnumMale:
		modelsGenderEnum = models.GenderEnumMale
	case models.GenderEnumNonBinary:
		modelsGenderEnum = models.GenderEnumNonBinary
	case models.GenderEnumTransgenderFemale:
		modelsGenderEnum = models.GenderEnumTransgenderFemale
	case models.GenderEnumTransgenderMale:
		modelsGenderEnum = models.GenderEnumTransgenderMale
	default: // ignored
	}
	return modelsGenderEnum
}
func (c *ModelConverterImpl) pTimeTimeToPTimeTime2(source *time.Time) *time.Time {
	var pTimeTime *time.Time
	if source != nil {
		timeTime := ConvertTime((*source))
		pTimeTime = &timeTime
	}
	return pTimeTime
}
func (c *ModelConverterImpl) uuidNullUUIDToUuidNullUUID(source uuid.NullUUID) uuid.NullUUID {
	var uuidNullUUID uuid.NullUUID
	uuidNullUUID.UUID = c.uuidUUIDToUuidUUID3(source.UUID)
	uuidNullUUID.Valid = source.Valid
	return uuidNullUUID
}
func (c *ModelConverterImpl) uuidUUIDToUuidUUID3(source uuid.UUID) uuid.UUID {
	var uuidUUID uuid.UUID
	for i := 0; i < len(source); i++ {
		uuidUUID[i] = source[i]
	}
	return uuidUUID
}

type UpdateParamsConverterImpl struct{}

func (c *UpdateParamsConverterImpl) ConvertEditToUpdateParams(source models.Edit) db.UpdateEditParams {
	var dbUpdateEditParams db.UpdateEditParams
	dbUpdateEditParams.ID = c.uuidUUIDToUuidUUID4(source.ID)
	dbUpdateEditParams.UserID = ConvertUUIDNullToNullUUID(source.UserID)
	dbUpdateEditParams.TargetType = source.TargetType
	dbUpdateEditParams.Operation = source.Operation
	dbUpdateEditParams.Data = ConvertJSONToBytes(source.Data)
	dbUpdateEditParams.Votes = source.VoteCount
	dbUpdateEditParams.Status = source.Status
	dbUpdateEditParams.Applied = source.Applied
	dbUpdateEditParams.UpdatedAt = c.pTimeTimeToPTimeTime3(source.UpdatedAt)
	return dbUpdateEditParams
}
func (c *UpdateParamsConverterImpl) ConvertPerformerToUpdateParams(source models.Performer) db.UpdatePerformerParams {
	var dbUpdatePerformerParams db.UpdatePerformerParams
	dbUpdatePerformerParams.ID = c.uuidUUIDToUuidUUID4(source.ID)
	dbUpdatePerformerParams.Name = source.Name
	if source.Disambiguation != nil {
		xstring := *source.Disambiguation
		dbUpdatePerformerParams.Disambiguation = &xstring
	}
	if source.Gender != nil {
		modelsGenderEnum := c.modelsGenderEnumToModelsGenderEnum3(*source.Gender)
		dbUpdatePerformerParams.Gender = &modelsGenderEnum
	}
	if source.BirthDate != nil {
		xstring2 := *source.BirthDate
		dbUpdatePerformerParams.Birthdate = &xstring2
	}
	dbUpdatePerformerParams.Ethnicity = ConvertEthnicityEnumToPgText(source.Ethnicity)
	if source.Country != nil {
		xstring3 := *source.Country
		dbUpdatePerformerParams.Country = &xstring3
	}
	dbUpdatePerformerParams.EyeColor = ConvertEyeColorEnumToPgText(source.EyeColor)
	dbUpdatePerformerParams.HairColor = ConvertHairColorEnumToPgText(source.HairColor)
	if source.Height != nil {
		xint := *source.Height
		dbUpdatePerformerParams.Height = &xint
	}
	if source.CupSize != nil {
		xstring4 := *source.CupSize
		dbUpdatePerformerParams.CupSize = &xstring4
	}
	if source.BandSize != nil {
		xint2 := *source.BandSize
		dbUpdatePerformerParams.BandSize = &xint2
	}
	if source.HipSize != nil {
		xint3 := *source.HipSize
		dbUpdatePerformerParams.HipSize = &xint3
	}
	if source.WaistSize != nil {
		xint4 := *source.WaistSize
		dbUpdatePerformerParams.WaistSize = &xint4
	}
	dbUpdatePerformerParams.BreastType = ConvertBreastTypeEnumToPgText(source.BreastType)
	if source.CareerStartYear != nil {
		xint5 := *source.CareerStartYear
		dbUpdatePerformerParams.CareerStartYear = &xint5
	}
	if source.CareerEndYear != nil {
		xint6 := *source.CareerEndYear
		dbUpdatePerformerParams.CareerEndYear = &xint6
	}
	dbUpdatePerformerParams.UpdatedAt = ConvertTime(source.Updated)
	dbUpdatePerformerParams.Deleted = source.Deleted
	if source.DeathDate != nil {
		xstring5 := *source.DeathDate
		dbUpdatePerformerParams.Deathdate = &xstring5
	}
	return dbUpdatePerformerParams
}
func (c *UpdateParamsConverterImpl) ConvertSceneToUpdateParams(source models.Scene) db.UpdateSceneParams {
	var dbUpdateSceneParams db.UpdateSceneParams
	dbUpdateSceneParams.ID = c.uuidUUIDToUuidUUID4(source.ID)
	if source.Title != nil {
		xstring := *source.Title
		dbUpdateSceneParams.Title = &xstring
	}
	if source.Details != nil {
		xstring2 := *source.Details
		dbUpdateSceneParams.Details = &xstring2
	}
	if source.Date != nil {
		xstring3 := *source.Date
		dbUpdateSceneParams.Date = &xstring3
	}
	if source.ProductionDate != nil {
		xstring4 := *source.ProductionDate
		dbUpdateSceneParams.ProductionDate = &xstring4
	}
	dbUpdateSceneParams.StudioID = ConvertUUIDNullToNullUUID(source.StudioID)
	dbUpdateSceneParams.UpdatedAt = ConvertTime(source.UpdatedAt)
	if source.Duration != nil {
		xint := *source.Duration
		dbUpdateSceneParams.Duration = &xint
	}
	if source.Director != nil {
		xstring5 := *source.Director
		dbUpdateSceneParams.Director = &xstring5
	}
	if source.Code != nil {
		xstring6 := *source.Code
		dbUpdateSceneParams.Code = &xstring6
	}
	dbUpdateSceneParams.Deleted = source.Deleted
	return dbUpdateSceneParams
}
func (c *UpdateParamsConverterImpl) ConvertSiteToUpdateParams(source models.Site) db.UpdateSiteParams {
	var dbUpdateSiteParams db.UpdateSiteParams
	dbUpdateSiteParams.ID = c.uuidUUIDToUuidUUID4(source.ID)
	dbUpdateSiteParams.Name = source.Name
	if source.Description != nil {
		xstring := *source.Description
		dbUpdateSiteParams.Description = &xstring
	}
	if source.URL != nil {
		xstring2 := *source.URL
		dbUpdateSiteParams.Url = &xstring2
	}
	if source.Regex != nil {
		xstring3 := *source.Regex
		dbUpdateSiteParams.Regex = &xstring3
	}
	if source.ValidTypes != nil {
		dbUpdateSiteParams.ValidTypes = make([]string, len(source.ValidTypes))
		for i := 0; i < len(source.ValidTypes); i++ {
			dbUpdateSiteParams.ValidTypes[i] = source.ValidTypes[i]
		}
	}
	dbUpdateSiteParams.UpdatedAt = ConvertTime(source.UpdatedAt)
	return dbUpdateSiteParams
}
func (c *UpdateParamsConverterImpl) modelsGenderEnumToModelsGenderEnum3(source models.GenderEnum) models.GenderEnum {
	var modelsGenderEnum models.GenderEnum
	switch source {
	case models.GenderEnumFemale:
		modelsGenderEnum = models.GenderEnumFemale
	case models.GenderEnumIntersex:
		modelsGenderEnum = models.GenderEnumIntersex
	case models.GenderEnumMale:
		modelsGenderEnum = models.GenderEnumMale
	case models.GenderEnumNonBinary:
		modelsGenderEnum = models.GenderEnumNonBinary
	case models.GenderEnumTransgenderFemale:
		modelsGenderEnum = models.GenderEnumTransgenderFemale
	case models.GenderEnumTransgenderMale:
		modelsGenderEnum = models.GenderEnumTransgenderMale
	default: // ignored
	}
	return modelsGenderEnum
}
func (c *UpdateParamsConverterImpl) pTimeTimeToPTimeTime3(source *time.Time) *time.Time {
	var pTimeTime *time.Time
	if source != nil {
		timeTime := ConvertTime((*source))
		pTimeTime = &timeTime
	}
	return pTimeTime
}
func (c *UpdateParamsConverterImpl) uuidUUIDToUuidUUID4(source uuid.UUID) uuid.UUID {
	var uuidUUID uuid.UUID
	for i := 0; i < len(source); i++ {
		uuidUUID[i] = source[i]
	}
	return uuidUUID
}
