// Code generated by go generate; DO NOT EDIT.
// The geometry of templates/*.psd, parsed offline by ./gen so the server
// carries no PSD parser. Regenerate with go generate after changing a
// template file; the drift test compares this table against the files.

package croptemplate

func builtinTemplates() map[string]Template {
	return map[string]Template{
		"CROP_BUST": {
			Width:  1000,
			Height: 1500,
			Guides: []Guide{
				{Axis: "X", Position: 0.25, Role: "REFERENCE", Label: "Left quarter"},
				{Axis: "X", Position: 0.75, Role: "REFERENCE", Label: "Right quarter"},
				{Axis: "Y", Position: 0.01, Role: "ANCHOR", Label: "Top of the hair"},
				{Axis: "Y", Position: 0.4, Role: "ANCHOR", Label: "Bottom of the chin"},
				{Axis: "Y", Position: 0.8, Role: "REFERENCE", Label: "Below the breastbone"},
				{Axis: "Y", Position: 0.99, Role: "MARGIN", Label: "Mid-waist"},
			},
		},
		"CROP_FACE": {
			Width:  1000,
			Height: 1500,
			Guides: []Guide{
				{Axis: "X", Position: 0.25, Role: "REFERENCE", Label: "Left quarter"},
				{Axis: "X", Position: 0.75, Role: "REFERENCE", Label: "Right quarter"},
				{Axis: "Y", Position: 0.01, Role: "ANCHOR", Label: "Top of the hair"},
				{Axis: "Y", Position: 0.4, Role: "ANCHOR", Label: "Bisects the eyes"},
				{Axis: "Y", Position: 0.8, Role: "REFERENCE", Label: "Bottom of the chin"},
				{Axis: "Y", Position: 0.99, Role: "MARGIN", Label: "Below the collarbone"},
			},
		},
		"CROP_FULL_BODY": {
			Width:  800,
			Height: 1200,
			Guides: []Guide{
				{Axis: "X", Position: 0.015, Role: "MARGIN", Label: "Left margin"},
				{Axis: "X", Position: 0.3325, Role: "REFERENCE", Label: "Left third"},
				{Axis: "X", Position: 0.66625, Role: "REFERENCE", Label: "Right third"},
				{Axis: "X", Position: 0.985, Role: "MARGIN", Label: "Right margin"},
				{Axis: "Y", Position: 0.01, Role: "ANCHOR", Label: "Top of the head"},
				{Axis: "Y", Position: 0.3325, Role: "REFERENCE", Label: "Upper third"},
				{Axis: "Y", Position: 0.6666666666666666, Role: "REFERENCE", Label: "Lower third"},
				{Axis: "Y", Position: 0.99, Role: "ANCHOR", Label: "The feet"},
			},
		},
		"CROP_HEADSHOT": {
			Width:  800,
			Height: 1200,
			Guides: []Guide{
				{Axis: "X", Position: 0.015, Role: "MARGIN", Label: "Left margin"},
				{Axis: "X", Position: 0.3325, Role: "REFERENCE", Label: "Left third"},
				{Axis: "X", Position: 0.66625, Role: "REFERENCE", Label: "Right third"},
				{Axis: "X", Position: 0.985, Role: "MARGIN", Label: "Right margin"},
				{Axis: "Y", Position: 0.01, Role: "ANCHOR", Label: "Top of the hair"},
				{Axis: "Y", Position: 0.3325, Role: "ANCHOR", Label: "Bisects the eyes"},
				{Axis: "Y", Position: 0.6666666666666666, Role: "REFERENCE", Label: "Bottom of the chin"},
				{Axis: "Y", Position: 0.99, Role: "MARGIN", Label: "Above the chest"},
			},
		},
		"CROP_THREE_QUARTER": {
			Width:  800,
			Height: 1200,
			Guides: []Guide{
				{Axis: "X", Position: 0.015, Role: "MARGIN", Label: "Left margin"},
				{Axis: "X", Position: 0.3325, Role: "REFERENCE", Label: "Left third"},
				{Axis: "X", Position: 0.66625, Role: "REFERENCE", Label: "Right third"},
				{Axis: "X", Position: 0.985, Role: "MARGIN", Label: "Right margin"},
				{Axis: "Y", Position: 0.01, Role: "ANCHOR", Label: "Top of the hair"},
				{Axis: "Y", Position: 0.3325, Role: "REFERENCE", Label: "Under the collarbone"},
				{Axis: "Y", Position: 0.9, Role: "ANCHOR", Label: "Bottom of the crotch"},
				{Axis: "Y", Position: 0.99, Role: "MARGIN", Label: "Mid-thigh"},
			},
		},
		"CROP_THREE_QUARTER_PLUS": {
			Width:  800,
			Height: 1200,
			Guides: []Guide{
				{Axis: "X", Position: 0.015, Role: "MARGIN", Label: "Left margin"},
				{Axis: "X", Position: 0.3325, Role: "REFERENCE", Label: "Left third"},
				{Axis: "X", Position: 0.66625, Role: "REFERENCE", Label: "Right third"},
				{Axis: "X", Position: 0.985, Role: "MARGIN", Label: "Right margin"},
				{Axis: "Y", Position: 0.01, Role: "ANCHOR", Label: "Top of the hair"},
				{Axis: "Y", Position: 0.3, Role: "REFERENCE", Label: "Under the collarbone"},
				{Axis: "Y", Position: 0.8, Role: "ANCHOR", Label: "Bottom of the crotch"},
				{Axis: "Y", Position: 0.99, Role: "MARGIN", Label: "Above the knees"},
			},
		},
		"CROP_TORSO": {
			Width:  800,
			Height: 1200,
			Guides: []Guide{
				{Axis: "X", Position: 0.015, Role: "MARGIN", Label: "Left margin"},
				{Axis: "X", Position: 0.3325, Role: "REFERENCE", Label: "Left third"},
				{Axis: "X", Position: 0.66625, Role: "REFERENCE", Label: "Right third"},
				{Axis: "X", Position: 0.985, Role: "MARGIN", Label: "Right margin"},
				{Axis: "Y", Position: 0.01, Role: "ANCHOR", Label: "Top of the hair"},
				{Axis: "Y", Position: 0.3325, Role: "ANCHOR", Label: "Bottom of the chin"},
				{Axis: "Y", Position: 0.8, Role: "REFERENCE", Label: "Mid-waist"},
				{Axis: "Y", Position: 0.99, Role: "MARGIN", Label: "Above the bikini line"},
			},
		},
		"CROP_WIDE": {
			Width:  1920,
			Height: 1080,
			Guides: []Guide{
				{Axis: "X", Position: 0.009375, Role: "MARGIN", Label: "Left margin"},
				{Axis: "X", Position: 0.3328125, Role: "REFERENCE", Label: "Left third"},
				{Axis: "X", Position: 0.6661458333333333, Role: "REFERENCE", Label: "Right third"},
				{Axis: "X", Position: 0.9895833333333334, Role: "MARGIN", Label: "Right margin"},
				{Axis: "Y", Position: 0.009259259259259259, Role: "MARGIN", Label: "Top margin"},
				{Axis: "Y", Position: 0.3314814814814815, Role: "REFERENCE", Label: "Upper third"},
				{Axis: "Y", Position: 0.6648148148148149, Role: "REFERENCE", Label: "Lower third"},
				{Axis: "Y", Position: 0.9888888888888889, Role: "MARGIN", Label: "Bottom margin"},
			},
		},
	}
}
