#import "../fragments/PerformerFragment.gql"
#import "../fragments/StudioFragment.gql"
#import "../fragments/ImageFragment.gql"
#import "../fragments/SceneFragment.gql"
#import "../fragments/TagFragment.gql"
#import "../fragments/CommentFragment.gql"
#import "../fragments/URLFragment.gql"
#import "../fragments/FingerprintFragment.gql"
fragment EditFragment on Edit {
  id
  target_type
  operation
  status
  applied
  created
  updated
  vote_count
  destructive
  comments {
    ...CommentFragment
  }
  votes {
    user {
      id
      name
    }
    date
    vote
  }
  user {
    id
    name
  }
  target {
    ... on Tag {
      id
      name
      description
      deleted
      category {
        id
        name
      }
    }
    ... on Performer {
      ...PerformerFragment
    }
    ... on Studio {
      ...StudioFragment
    }
    ... on Scene {
      ...SceneFragment
    }
  }
  details {
    ... on TagEdit {
      name
      description
      added_aliases
      removed_aliases
      category {
        id
        name
      }
    }
    ... on PerformerEdit {
      name
      disambiguation
      added_aliases
      removed_aliases
      gender
      added_urls {
        ...URLFragment
      }
      removed_urls {
        ...URLFragment
      }
      birthdate
      birthdate_accuracy
      ethnicity
      country
      eye_color
      hair_color
      height
      cup_size
      band_size
      waist_size
      hip_size
      breast_type
      career_start_year
      career_end_year
      added_tattoos {
        location
        description
      }
      removed_tattoos {
        location
        description
      }
      added_piercings {
        location
        description
      }
      removed_piercings {
        location
        description
      }
      added_images {
        ...ImageFragment
      }
      removed_images {
        ...ImageFragment
      }
      draft_id
    }
    ... on StudioEdit {
      name
      added_urls {
        ...URLFragment
      }
      removed_urls {
        ...URLFragment
      }
      parent {
        ...StudioFragment
      }
      added_images {
        ...ImageFragment
      }
      removed_images {
        ...ImageFragment
      }
    }
    ... on SceneEdit {
      title
      details
      added_urls {
        ...URLFragment
      }
      removed_urls {
        ...URLFragment
      }
      date
      studio {
        ...StudioFragment
      }
      added_performers {
        performer {
          ...PerformerFragment
        }
        as
      }
      removed_performers {
        performer {
          ...PerformerFragment
        }
        as
      }
      added_tags {
        ...TagFragment
      }
      removed_tags {
        ...TagFragment
      }
      added_images {
        ...ImageFragment
      }
      removed_images {
        ...ImageFragment
      }
      added_fingerprints {
        ...FingerprintFragment
      }
      removed_fingerprints {
        ...FingerprintFragment
      }
      duration
      director
      code
      draft_id
    }
  }
  old_details {
    ... on TagEdit {
      name
      description
      category {
        id
        name
      }
    }
    ... on PerformerEdit {
      name
      disambiguation
      gender
      birthdate
      birthdate_accuracy
      ethnicity
      country
      eye_color
      hair_color
      height
      cup_size
      band_size
      waist_size
      hip_size
      breast_type
      career_start_year
      career_end_year
    }
    ... on StudioEdit {
      name
      parent {
        ...StudioFragment
      }
    }
    ... on SceneEdit {
      title
      details
      added_urls {
        ...URLFragment
      }
      removed_urls {
        ...URLFragment
      }
      date
      studio {
        ...StudioFragment
      }
      added_performers {
        performer {
          ...PerformerFragment
        }
        as
      }
      removed_performers {
        performer {
          ...PerformerFragment
        }
        as
      }
      added_tags {
        ...TagFragment
      }
      removed_tags {
        ...TagFragment
      }
      added_images {
        ...ImageFragment
      }
      removed_images {
        ...ImageFragment
      }
      added_fingerprints {
        ...FingerprintFragment
      }
      removed_fingerprints {
        ...FingerprintFragment
      }
      duration
      director
      code
    }
  }
  merge_sources {
    ... on Tag {
      id
      name
      description
      deleted
      category {
        id
        name
      }
    }
    ... on Performer {
      ...PerformerFragment
    }
    ... on Studio {
      ...StudioFragment
    }
    ... on Scene {
      ...SceneFragment
    }
  }
  options {
    set_modify_aliases
    set_merge_aliases
  }
}
