#import "../fragments/ImageFragment.gql"\nfragment PairingSceneFragment on Scene {\n  id\n  title\n  duration\n  release_date\n  studio {\n    id\n    name\n  }\n  images {\n    ...ImageFragment\n  }\n}\n