#import "../fragments/ImageFragment.gql"\n#import "../fragments/URLFragment.gql"\nfragment PerformerFragment on Performer {\n  id\n  name\n  disambiguation\n  deleted\n  merged_into_id\n  aliases\n  gender\n  birth_date\n  death_date\n  age\n  height\n  hair_color\n  eye_color\n  ethnicity\n  country\n  career_end_year\n  career_start_year\n  breast_type\n  waist_size\n  hip_size\n  band_size\n  cup_size\n  tattoos {\n    location\n    description\n  }\n  piercings {\n    location\n    description\n  }\n  urls {\n    ...URLFragment\n  }\n  images {\n    ...ImageFragment\n  }\n  is_favorite\n}\n