#import "../fragments/ImageFragment.gql"
#import "../fragments/URLFragment.gql"
fragment PerformerFragment on Performer {
  id
  name
  disambiguation
  deleted
  merged_into_id
  aliases
  gender
  birth_date
  death_date
  age
  height
  hair_color
  eye_color
  ethnicity
  country
  career_end_year
  career_start_year
  breast_type
  waist_size
  hip_size
  band_size
  cup_size
  tattoos {
    location
    description
  }
  piercings {
    location
    description
  }
  urls {
    ...URLFragment
  }
  images {
    ...ImageFragment
  }
  is_favorite
}
