#import "../fragments/URLFragment.gql"\n#import "../fragments/ImageFragment.gql"\n#import "../fragments/ScenePerformerFragment.gql"\nfragment QuerySceneFragment on Scene {\n  id\n  release_date\n  title\n  duration\n  urls {\n    ...URLFragment\n  }\n  images {\n    ...ImageFragment\n  }\n  studio {\n    id\n    name\n  }\n  performers {\n    as\n    performer {\n      ...ScenePerformerFragment\n    }\n  }\n}\n