#import "../fragments/URLFragment.gql"
#import "../fragments/ImageFragment.gql"
#import "../fragments/ScenePerformerFragment.gql"
fragment QuerySceneFragment on Scene {
  id
  release_date
  title
  code
  duration
  urls {
    ...URLFragment
  }
  images {
    ...ImageFragment
  }
  studio {
    id
    name
  }
  performers {
    as
    performer {
      ...ScenePerformerFragment
    }
  }
}
