#import "../fragments/URLFragment.gql"
#import "../fragments/ImageFragment.gql"
#import "../fragments/ScenePerformerFragment.gql"
fragment QuerySceneFragment on Scene {
  id
  date {
    date
    accuracy
  }
  title
  duration
  urls {
    ...URLFragment
  }
  images {
    ...ImageFragment
  }
  studio {
    id
    name
  }
  performers {
    as
    performer {
      ...ScenePerformerFragment
    }
  }
}
