#import "../fragments/ImageFragment.gql"
#import "../fragments/ScenePerformerFragment.gql"
fragment SceneFragment on Scene {
  id
  date
  title
  deleted
  details
  director
  duration
  urls {
    url
    type
  }
  images {
    ...ImageFragment
  }
  studio {
    id
    name
  }
  performers {
    as
    performer {
      ...ScenePerformerFragment
    }
  }
  fingerprints {
    hash
    algorithm
    duration
    submissions
    user_submitted
    created
    updated
  }
  tags {
    id
    name
    description
  }
}
