#import "../fragments/ImageFragment.gql"\n#import "../fragments/URLFragment.gql"\nfragment SearchPerformerFragment on Performer {\n  id\n  name\n  disambiguation\n  deleted\n  gender\n  aliases\n  country\n  career_start_year\n  career_end_year\n  scene_count\n  birth_date\n  urls {\n    ...URLFragment\n  }\n  images {\n    ...ImageFragment\n  }\n  is_favorite\n}\n