#import "../fragments/ImageFragment.gql"
#import "../fragments/URLFragment.gql"
fragment SearchPerformerFragment on Performer {
  id
  name
  disambiguation
  deleted
  gender
  aliases
  country
  career_start_year
  career_end_year
  scene_count
  birthdate {
    date
    accuracy
  }
  urls {
    ...URLFragment
  }
  images {
    ...ImageFragment
  }
}
