#import "../fragments/URLFragment.gql"\nfragment StudioFragment on Studio {\n  id\n  name\n  aliases\n  parent {\n    id\n    name\n  }\n  urls {\n    ...URLFragment\n  }\n  images {\n    id\n    url\n    height\n    width\n  }\n  deleted\n  is_favorite\n}\n