query Drafts {
  findDrafts {
    id
    created
    expires
    data {
      ... on PerformerDraft {
        id
        name
      }
      ... on SceneDraft {
        id
        title
      }
    }
  }
}
