#import "../fragments/PairingSceneFragment.gql"
query PairingScenes(
  $performerId: ID!
  $partnerId: ID!
  $page: Int!
  $per_page: Int!
) {
  findPerformer(id: $partnerId) {
    id
    queryScenes(
      input: {
        performers: { modifier: INCLUDES_ALL, value: [$performerId] }
        page: $page
        per_page: $per_page
        sort: DATE
        direction: DESC
      }
    ) {
      scenes {
        ...PairingSceneFragment
      }
    }
  }
}
