#import "../fragments/URLFragment.gql"
#import "../fragments/ImageFragment.gql"
query Performers($input: PerformerQueryInput!) {
  queryPerformers(input: $input) {
    count
    performers {
      id
      name
      disambiguation
      deleted
      aliases
      gender
      birthdate {
        date
        accuracy
      }
      age
      height
      hair_color
      eye_color
      ethnicity
      country
      career_end_year
      career_start_year
      breast_type
      waist_size
      hip_size
      band_size
      cup_size
      tattoos {
        location
        description
      }
      piercings {
        location
        description
      }
      urls {
        ...URLFragment
      }
      images {
        ...ImageFragment
      }
      is_favorite
    }
  }
}
