#import "../fragments/ImageFragment.gql"
query Performers($input: PerformerQueryInput!) {
  queryPerformers(input: $input) {
    count
    performers {
      id
      name
      disambiguation
      deleted
      gender
      images {
        ...ImageFragment
      }
      is_favorite
    }
  }
}
