#import "../fragments/ImageFragment.gql"
query ScenePairings(
  $performerId: ID!
  $names: String
  $gender: GenderFilterEnum
  $favorite: Boolean
  $page: Int! = 1
  $per_page: Int! = 25
  $direction: SortDirectionEnum!
  $sort: PerformerSortEnum!
  $fetchScenes: Boolean!
) {
  queryPerformers(
    input: {
      performed_with: $performerId
      names: $names
      gender: $gender
      is_favorite: $favorite
      page: $page
      per_page: $per_page
      direction: $direction
      sort: $sort
    }
  ) {
    count
    performers {
      id
      name
      disambiguation
      deleted
      aliases
      gender
      birth_date
      is_favorite
      images {
        ...ImageFragment
      }
      scenes(input: { performed_with: $performerId })
        @include(if: $fetchScenes) {
        id
        title
        date
        duration
        code
        release_date
        studio {
          id
          name
        }
        images {
          ...ImageFragment
        }
      }
    }
  }
}
