#import "../fragments/QuerySceneFragment.gql"
query Scenes($filter: QuerySpec, $sceneFilter: SceneFilterType) {
  queryScenes(filter: $filter, scene_filter: $sceneFilter) {
    count
    scenes {
      ...QuerySceneFragment
    }
  }
}
