#import "../fragments/ImageFragment.gql"
#import "../fragments/URLFragment.gql"
query SearchScenes($term: String!, $page: Int, $per_page: Int) {
  searchScene(term: $term, page: $page, per_page: $per_page) {
    count
    scenes {
      id
      release_date
      title
      deleted
      duration
      code
      urls {
        ...URLFragment
      }
      images {
        ...ImageFragment
      }
      studio {
        id
        name
      }
      performers {
        as
        performer {
          id
          name
          disambiguation
          gender
          aliases
          deleted
        }
      }
    }
  }
}
