query Sites {
  querySites {
    sites {
      id
      name
      description
      url
      regex
      valid_types
      category {
        id
        name
        sort_order
      }
      highlighted
      icon
      created
      updated
    }
  }
}
