query Site($id: ID!) {
  findSite(id: $id) {
    id
    name
    description
    url
    regex
    valid_types
    category {
      id
      name
      sort_order
    }
    icon
    created
    updated
  }
}
