#import "../fragments/ImageFragment.gql"
query StudioPerformers(
  $studioId: ID!
  $gender: GenderFilterEnum
  $favorite: Boolean
  $names: String
  $page: Int! = 1
  $per_page: Int! = 25
  $direction: SortDirectionEnum!
  $sort: PerformerSortEnum!
) {
  queryPerformers(
    input: {
      studio_id: $studioId
      gender: $gender
      is_favorite: $favorite
      names: $names
      page: $page
      per_page: $per_page
      direction: $direction
      sort: $sort
    }
  ) {
    count
    performers {
      id
      name
      disambiguation
      deleted
      aliases
      gender
      birth_date
      is_favorite
      images {
        ...ImageFragment
      }
      scenes(input: { studio_id: $studioId }) {
        id
        title
        date
        duration
        code
        release_date
        studio {
          id
          name
        }
        images {
          ...ImageFragment
        }
      }
    }
  }
}
