#import "../fragments/ImageFragment.gql"
#import "../fragments/PairingSceneFragment.gql"
query StudioPerformers(
  $studioId: ID!
  $gender: GenderFilterEnum
  $favorite: Boolean
  $names: String
  $page: Int! = 1
  $per_page: Int! = 25
  $direction: SortDirectionEnum!
  $sort: PerformerSortEnum!
  $scenesPerPage: Int! = 12
) {
  queryPerformers(
    input: {
      studio_id: $studioId
      gender: $gender
      is_favorite: $favorite
      names: $names
      page: $page
      per_page: $per_page
      direction: $direction
      sort: $sort
    }
  ) {
    count
    performers {
      id
      name
      deleted
      gender
      is_favorite
      images {
        ...ImageFragment
      }
      queryScenes(
        input: {
          studios: { modifier: INCLUDES, value: [$studioId] }
          page: 1
          per_page: $scenesPerPage
          sort: DATE
          direction: DESC
        }
      ) {
        count
        scenes {
          ...PairingSceneFragment
        }
      }
    }
  }
}
