#import "../fragments/URLFragment.gql"
#import "../fragments/ImageFragment.gql"
query Studios($filter: QuerySpec, $studioFilter: StudioFilterType) {
  queryStudios(filter: $filter, studio_filter: $studioFilter) {
      count
      studios {
        id
        name
        parent {
            id,
            name
        }
        urls {
          ...URLFragment
        }
        images {
          ...ImageFragment
        }
      }
  }
}
