query Users($input: UserQueryInput!) {
  queryUsers(input: $input) {
    count
    users {
      id
      name
      email
      roles
      api_key
      api_calls
      invited_by {
        id
        name
      }
      invite_tokens
    }
  }
}
