query User($name: String!) {
  findUser(username: $name) {
    id
    name
    email
    roles
    api_key
    api_calls
    invited_by {
      id
      name
    }
    invite_tokens
    active_invite_codes
    vote_count {
      accept
      reject
      immediate_accept
      immediate_reject
      abstain
    }
    edit_count {
      immediate_accepted
      immediate_rejected
      accepted
      rejected
      failed
      canceled
      pending
    }
  }
}
