query Performers($filter: QuerySpec, $performerFilter: PerformerFilterType) {
  queryPerformers(filter: $filter, performer_filter: $performerFilter) {
    count
    performers {
      id
      name
      disambiguation
      aliases
      gender
      birthdate {
        date
        accuracy
      }
      age
      height
      hair_color
      eye_color
      ethnicity
      country
      career_end_year
      career_start_year
      breast_type
      measurements {
        waist
        hip
        band_size
        cup_size
      }
      tattoos {
        location
        description
      }
      piercings {
        location
        description
      }
      urls {
          type
          url
          image_id
          height
          width
      }
    }
  }
}
