query Scenes($filter: QuerySpec, $sceneFilter: SceneFilterType) {
  queryScenes(filter: $filter, scene_filter: $sceneFilter) {
        count
        scenes {
            id
            date
            title
            duration
            urls {
                url
                type
            }
            studio {
                id
                name
            }
            performers {
                performer {
                    id
                    name
                    gender
                }
            }

        }
    }
}
