#import "./ImageFragment.gql"
#import "./ScenePerformerFragment.gql"
query Scenes($filter: QuerySpec, $sceneFilter: SceneFilterType) {
  queryScenes(filter: $filter, scene_filter: $sceneFilter) {
    count
    scenes {
      id
      date
      title
      duration
      urls {
        url
        type
      }
      images {
        ...ImageFragment
      }
      studio {
        id
        name
      }
      performers {
        as
        performer {
          ...ScenePerformerFragment
        }
      }
    }
  }
}
