#import "./ImageFragment.gql"
#import "./SearchPerformerFragment.gql"
query SearchAll($term: String!) {
    searchPerformer(term: $term) {
      ...SearchPerformerFragment
    }
    searchScene(term: $term) {
        id
        date
        title
        urls {
            url
            type
        }
        images {
          ...ImageFragment
        }
        studio {
            id
            name
        }
        performers {
            as
            performer {
                id
                name
                disambiguation
                gender
                aliases
                deleted
            }
        }
    }
}
