mutation Search($term: String!, $searchType: String!) {
    search(term: $term, searchType: $searchType) {
        performers {
            uuid
            id
            name
            birthdate
            birthday
            displayName
            disambiguation
            photoUrl
            gender
            aliases
        }
        scenes {
            id
            uuid
            title
            date
            dateAccuracy
            photoUrl
            studio {
                id
                title
                uuid
            }
            performers {
                alias
                performer {
                    name
                    displayName
                    uuid
                    id
                    gender
                }
            }
        }
    }
}
