query Studios($filter: QuerySpec, $studioFilter: StudioFilterType) {
  queryStudios(filter: $filter, studio_filter: $studioFilter) {
      count
      studios {
        id
        name
        parent {
            id,
            name
        }
        urls {
            url
            type
        }
        images {
            id
            url
            height
            width
        }
      }
  }
}
