query Users {
  queryUsers(user_filter: {}) {
    users {
      id
      name
      email
      roles
      api_key
      api_calls
      invited_by {
        id
        name
      }
      invite_tokens
    }
  }
}
