// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: copyfrom.go

package queries

import (
	"context"
)

// iteratorForCreateFingerprints implements pgx.CopyFromSource.
type iteratorForCreateFingerprints struct {
	rows                 []CreateFingerprintsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateFingerprints) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateFingerprints) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Hash,
		r.rows[0].Algorithm,
	}, nil
}

func (r iteratorForCreateFingerprints) Err() error {
	return nil
}

func (q *Queries) CreateFingerprints(ctx context.Context, arg []CreateFingerprintsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"fingerprints"}, []string{"hash", "algorithm"}, &iteratorForCreateFingerprints{rows: arg})
}

// iteratorForCreatePerformerAliases implements pgx.CopyFromSource.
type iteratorForCreatePerformerAliases struct {
	rows                 []CreatePerformerAliasesParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreatePerformerAliases) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreatePerformerAliases) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].PerformerID,
		r.rows[0].Alias,
	}, nil
}

func (r iteratorForCreatePerformerAliases) Err() error {
	return nil
}

func (q *Queries) CreatePerformerAliases(ctx context.Context, arg []CreatePerformerAliasesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"performer_aliases"}, []string{"performer_id", "alias"}, &iteratorForCreatePerformerAliases{rows: arg})
}

// iteratorForCreatePerformerImages implements pgx.CopyFromSource.
type iteratorForCreatePerformerImages struct {
	rows                 []CreatePerformerImagesParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreatePerformerImages) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreatePerformerImages) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].PerformerID,
		r.rows[0].ImageID,
	}, nil
}

func (r iteratorForCreatePerformerImages) Err() error {
	return nil
}

func (q *Queries) CreatePerformerImages(ctx context.Context, arg []CreatePerformerImagesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"performer_images"}, []string{"performer_id", "image_id"}, &iteratorForCreatePerformerImages{rows: arg})
}

// iteratorForCreatePerformerPiercings implements pgx.CopyFromSource.
type iteratorForCreatePerformerPiercings struct {
	rows                 []CreatePerformerPiercingsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreatePerformerPiercings) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreatePerformerPiercings) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].PerformerID,
		r.rows[0].Location,
		r.rows[0].Description,
	}, nil
}

func (r iteratorForCreatePerformerPiercings) Err() error {
	return nil
}

func (q *Queries) CreatePerformerPiercings(ctx context.Context, arg []CreatePerformerPiercingsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"performer_piercings"}, []string{"performer_id", "location", "description"}, &iteratorForCreatePerformerPiercings{rows: arg})
}

// iteratorForCreatePerformerTattoos implements pgx.CopyFromSource.
type iteratorForCreatePerformerTattoos struct {
	rows                 []CreatePerformerTattoosParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreatePerformerTattoos) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreatePerformerTattoos) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].PerformerID,
		r.rows[0].Location,
		r.rows[0].Description,
	}, nil
}

func (r iteratorForCreatePerformerTattoos) Err() error {
	return nil
}

func (q *Queries) CreatePerformerTattoos(ctx context.Context, arg []CreatePerformerTattoosParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"performer_tattoos"}, []string{"performer_id", "location", "description"}, &iteratorForCreatePerformerTattoos{rows: arg})
}

// iteratorForCreatePerformerURLs implements pgx.CopyFromSource.
type iteratorForCreatePerformerURLs struct {
	rows                 []CreatePerformerURLsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreatePerformerURLs) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreatePerformerURLs) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].PerformerID,
		r.rows[0].Url,
		r.rows[0].SiteID,
	}, nil
}

func (r iteratorForCreatePerformerURLs) Err() error {
	return nil
}

func (q *Queries) CreatePerformerURLs(ctx context.Context, arg []CreatePerformerURLsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"performer_urls"}, []string{"performer_id", "url", "site_id"}, &iteratorForCreatePerformerURLs{rows: arg})
}

// iteratorForCreateSceneFingerprints implements pgx.CopyFromSource.
type iteratorForCreateSceneFingerprints struct {
	rows                 []CreateSceneFingerprintsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateSceneFingerprints) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateSceneFingerprints) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].FingerprintID,
		r.rows[0].SceneID,
		r.rows[0].UserID,
		r.rows[0].Duration,
	}, nil
}

func (r iteratorForCreateSceneFingerprints) Err() error {
	return nil
}

func (q *Queries) CreateSceneFingerprints(ctx context.Context, arg []CreateSceneFingerprintsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"scene_fingerprints"}, []string{"fingerprint_id", "scene_id", "user_id", "duration"}, &iteratorForCreateSceneFingerprints{rows: arg})
}

// iteratorForCreateSceneImages implements pgx.CopyFromSource.
type iteratorForCreateSceneImages struct {
	rows                 []CreateSceneImagesParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateSceneImages) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateSceneImages) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].SceneID,
		r.rows[0].ImageID,
	}, nil
}

func (r iteratorForCreateSceneImages) Err() error {
	return nil
}

func (q *Queries) CreateSceneImages(ctx context.Context, arg []CreateSceneImagesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"scene_images"}, []string{"scene_id", "image_id"}, &iteratorForCreateSceneImages{rows: arg})
}

// iteratorForCreateScenePerformers implements pgx.CopyFromSource.
type iteratorForCreateScenePerformers struct {
	rows                 []CreateScenePerformersParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateScenePerformers) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateScenePerformers) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].SceneID,
		r.rows[0].PerformerID,
		r.rows[0].As,
	}, nil
}

func (r iteratorForCreateScenePerformers) Err() error {
	return nil
}

// Scene performers
func (q *Queries) CreateScenePerformers(ctx context.Context, arg []CreateScenePerformersParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"scene_performers"}, []string{"scene_id", "performer_id", "as"}, &iteratorForCreateScenePerformers{rows: arg})
}

// iteratorForCreateSceneTags implements pgx.CopyFromSource.
type iteratorForCreateSceneTags struct {
	rows                 []CreateSceneTagsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateSceneTags) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateSceneTags) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].SceneID,
		r.rows[0].TagID,
	}, nil
}

func (r iteratorForCreateSceneTags) Err() error {
	return nil
}

// Scene tags management
func (q *Queries) CreateSceneTags(ctx context.Context, arg []CreateSceneTagsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"scene_tags"}, []string{"scene_id", "tag_id"}, &iteratorForCreateSceneTags{rows: arg})
}

// iteratorForCreateSceneURLs implements pgx.CopyFromSource.
type iteratorForCreateSceneURLs struct {
	rows                 []CreateSceneURLsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateSceneURLs) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateSceneURLs) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].SceneID,
		r.rows[0].Url,
		r.rows[0].SiteID,
	}, nil
}

func (r iteratorForCreateSceneURLs) Err() error {
	return nil
}

// Scene URLs
func (q *Queries) CreateSceneURLs(ctx context.Context, arg []CreateSceneURLsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"scene_urls"}, []string{"scene_id", "url", "site_id"}, &iteratorForCreateSceneURLs{rows: arg})
}

// iteratorForCreateStudioAliases implements pgx.CopyFromSource.
type iteratorForCreateStudioAliases struct {
	rows                 []CreateStudioAliasesParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateStudioAliases) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateStudioAliases) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].StudioID,
		r.rows[0].Alias,
	}, nil
}

func (r iteratorForCreateStudioAliases) Err() error {
	return nil
}

// Studio aliases
func (q *Queries) CreateStudioAliases(ctx context.Context, arg []CreateStudioAliasesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"studio_aliases"}, []string{"studio_id", "alias"}, &iteratorForCreateStudioAliases{rows: arg})
}

// iteratorForCreateStudioImages implements pgx.CopyFromSource.
type iteratorForCreateStudioImages struct {
	rows                 []CreateStudioImagesParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateStudioImages) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateStudioImages) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].StudioID,
		r.rows[0].ImageID,
	}, nil
}

func (r iteratorForCreateStudioImages) Err() error {
	return nil
}

// Studio images
func (q *Queries) CreateStudioImages(ctx context.Context, arg []CreateStudioImagesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"studio_images"}, []string{"studio_id", "image_id"}, &iteratorForCreateStudioImages{rows: arg})
}

// iteratorForCreateStudioURLs implements pgx.CopyFromSource.
type iteratorForCreateStudioURLs struct {
	rows                 []CreateStudioURLsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateStudioURLs) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateStudioURLs) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].StudioID,
		r.rows[0].Url,
		r.rows[0].SiteID,
	}, nil
}

func (r iteratorForCreateStudioURLs) Err() error {
	return nil
}

// Studio URLs
func (q *Queries) CreateStudioURLs(ctx context.Context, arg []CreateStudioURLsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"studio_urls"}, []string{"studio_id", "url", "site_id"}, &iteratorForCreateStudioURLs{rows: arg})
}

// iteratorForCreateTagAliases implements pgx.CopyFromSource.
type iteratorForCreateTagAliases struct {
	rows                 []CreateTagAliasesParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateTagAliases) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateTagAliases) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].TagID,
		r.rows[0].Alias,
	}, nil
}

func (r iteratorForCreateTagAliases) Err() error {
	return nil
}

// Tag aliases
func (q *Queries) CreateTagAliases(ctx context.Context, arg []CreateTagAliasesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"tag_aliases"}, []string{"tag_id", "alias"}, &iteratorForCreateTagAliases{rows: arg})
}

// iteratorForCreateUserNotificationSubscriptions implements pgx.CopyFromSource.
type iteratorForCreateUserNotificationSubscriptions struct {
	rows                 []CreateUserNotificationSubscriptionsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateUserNotificationSubscriptions) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateUserNotificationSubscriptions) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].UserID,
		r.rows[0].Type,
	}, nil
}

func (r iteratorForCreateUserNotificationSubscriptions) Err() error {
	return nil
}

// User notification subscriptions
func (q *Queries) CreateUserNotificationSubscriptions(ctx context.Context, arg []CreateUserNotificationSubscriptionsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"user_notifications"}, []string{"user_id", "type"}, &iteratorForCreateUserNotificationSubscriptions{rows: arg})
}

// iteratorForCreateUserRoles implements pgx.CopyFromSource.
type iteratorForCreateUserRoles struct {
	rows                 []CreateUserRolesParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateUserRoles) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateUserRoles) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].UserID,
		r.rows[0].Role,
	}, nil
}

func (r iteratorForCreateUserRoles) Err() error {
	return nil
}

// User roles
func (q *Queries) CreateUserRoles(ctx context.Context, arg []CreateUserRolesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"user_roles"}, []string{"user_id", "role"}, &iteratorForCreateUserRoles{rows: arg})
}
