// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: fingerprint.sql

package queries

import (
	"context"
	"time"

	"github.com/gofrs/uuid"
)

const createFingerprint = `-- name: CreateFingerprint :one

INSERT INTO fingerprints (hash, algorithm) VALUES ($1, $2)
ON CONFLICT (hash, algorithm) DO UPDATE SET hash = EXCLUDED.hash
RETURNING id, algorithm, hash
`

type CreateFingerprintParams struct {
	Hash      int64  `db:"hash" json:"hash"`
	Algorithm string `db:"algorithm" json:"algorithm"`
}

// Fingerprint queries (normalized schema)
func (q *Queries) CreateFingerprint(ctx context.Context, arg CreateFingerprintParams) (Fingerprint, error) {
	row := q.db.QueryRow(ctx, createFingerprint, arg.Hash, arg.Algorithm)
	var i Fingerprint
	err := row.Scan(&i.ID, &i.Algorithm, &i.Hash)
	return i, err
}

const createOrReplaceFingerprint = `-- name: CreateOrReplaceFingerprint :exec
INSERT INTO scene_fingerprints (fingerprint_id, scene_id, user_id, duration, vote)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT ON CONSTRAINT scene_fingerprints_scene_id_fingerprint_id_user_id_key
DO UPDATE SET
    duration = EXCLUDED.duration,
    vote = EXCLUDED.vote
`

type CreateOrReplaceFingerprintParams struct {
	FingerprintID int       `db:"fingerprint_id" json:"fingerprint_id"`
	SceneID       uuid.UUID `db:"scene_id" json:"scene_id"`
	UserID        uuid.UUID `db:"user_id" json:"user_id"`
	Duration      int       `db:"duration" json:"duration"`
	Vote          int16     `db:"vote" json:"vote"`
}

func (q *Queries) CreateOrReplaceFingerprint(ctx context.Context, arg CreateOrReplaceFingerprintParams) error {
	_, err := q.db.Exec(ctx, createOrReplaceFingerprint,
		arg.FingerprintID,
		arg.SceneID,
		arg.UserID,
		arg.Duration,
		arg.Vote,
	)
	return err
}

type CreateSceneFingerprintsParams struct {
	FingerprintID int       `db:"fingerprint_id" json:"fingerprint_id"`
	SceneID       uuid.UUID `db:"scene_id" json:"scene_id"`
	UserID        uuid.UUID `db:"user_id" json:"user_id"`
	Duration      int       `db:"duration" json:"duration"`
}

const deleteAllSceneFingerprintSubmissions = `-- name: DeleteAllSceneFingerprintSubmissions :execrows
DELETE FROM scene_fingerprints SFP
USING fingerprints FP
WHERE SFP.fingerprint_id = FP.id
  AND FP.hash = $1
  AND FP.algorithm = $2
  AND SFP.scene_id = $3
`

type DeleteAllSceneFingerprintSubmissionsParams struct {
	Hash      int64     `db:"hash" json:"hash"`
	Algorithm string    `db:"algorithm" json:"algorithm"`
	SceneID   uuid.UUID `db:"scene_id" json:"scene_id"`
}

func (q *Queries) DeleteAllSceneFingerprintSubmissions(ctx context.Context, arg DeleteAllSceneFingerprintSubmissionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAllSceneFingerprintSubmissions, arg.Hash, arg.Algorithm, arg.SceneID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteDuplicateSceneFingerprintSubmissions = `-- name: DeleteDuplicateSceneFingerprintSubmissions :execrows
DELETE FROM scene_fingerprints SFP
USING fingerprints FP
WHERE SFP.fingerprint_id = FP.id
  AND FP.hash = $1
  AND FP.algorithm = $2
  AND SFP.scene_id = $3
  AND EXISTS (
    SELECT 1 FROM scene_fingerprints SFP2
    WHERE SFP2.scene_id = $4
      AND SFP2.fingerprint_id = SFP.fingerprint_id
      AND SFP2.user_id = SFP.user_id
  )
`

type DeleteDuplicateSceneFingerprintSubmissionsParams struct {
	Hash          int64     `db:"hash" json:"hash"`
	Algorithm     string    `db:"algorithm" json:"algorithm"`
	SourceSceneID uuid.UUID `db:"source_scene_id" json:"source_scene_id"`
	TargetSceneID uuid.UUID `db:"target_scene_id" json:"target_scene_id"`
}

// Delete source-scene submissions whose (fingerprint, user) already exists on the target scene,
// so MoveSceneFingerprintSubmissions can move the remainder without tripping the unique constraint.
func (q *Queries) DeleteDuplicateSceneFingerprintSubmissions(ctx context.Context, arg DeleteDuplicateSceneFingerprintSubmissionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDuplicateSceneFingerprintSubmissions,
		arg.Hash,
		arg.Algorithm,
		arg.SourceSceneID,
		arg.TargetSceneID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSceneFingerprint = `-- name: DeleteSceneFingerprint :exec
DELETE FROM scene_fingerprints SFP
USING fingerprints FP
WHERE SFP.fingerprint_id = FP.id
AND FP.hash = $1
AND FP.algorithm = $2
AND user_id = $3
AND scene_id = $4
`

type DeleteSceneFingerprintParams struct {
	Hash      int64     `db:"hash" json:"hash"`
	Algorithm string    `db:"algorithm" json:"algorithm"`
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
	SceneID   uuid.UUID `db:"scene_id" json:"scene_id"`
}

func (q *Queries) DeleteSceneFingerprint(ctx context.Context, arg DeleteSceneFingerprintParams) error {
	_, err := q.db.Exec(ctx, deleteSceneFingerprint,
		arg.Hash,
		arg.Algorithm,
		arg.UserID,
		arg.SceneID,
	)
	return err
}

const deleteSceneFingerprintsByScene = `-- name: DeleteSceneFingerprintsByScene :exec
DELETE FROM scene_fingerprints WHERE scene_id = $1
`

func (q *Queries) DeleteSceneFingerprintsByScene(ctx context.Context, sceneID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSceneFingerprintsByScene, sceneID)
	return err
}

const expandPhashNeighbors = `-- name: ExpandPhashNeighbors :many
SELECT DISTINCT FP.id, FP.hash
FROM UNNEST($1::BIGINT[]) phash
JOIN fingerprints FP
  ON FP.hash <@ (phash, $2::INTEGER)
  AND FP.algorithm = 'PHASH'
`

type ExpandPhashNeighborsParams struct {
	Hashes   []int64 `db:"hashes" json:"hashes"`
	Distance int     `db:"distance" json:"distance"`
}

type ExpandPhashNeighborsRow struct {
	ID   int   `db:"id" json:"id"`
	Hash int64 `db:"hash" json:"hash"`
}

// The pg-spgist_hamming custom-scan hook turns this UNNEST + <@ into a single
// batch BK-tree traversal when ≤64 hashes are supplied; caller must chunk.
// The scene_id join is intentionally NOT here: the planner overestimates the
// customscan's row count and picks a hash-join + seq scan of scene_fingerprints.
func (q *Queries) ExpandPhashNeighbors(ctx context.Context, arg ExpandPhashNeighborsParams) ([]ExpandPhashNeighborsRow, error) {
	rows, err := q.db.Query(ctx, expandPhashNeighbors, arg.Hashes, arg.Distance)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpandPhashNeighborsRow{}
	for rows.Next() {
		var i ExpandPhashNeighborsRow
		if err := rows.Scan(&i.ID, &i.Hash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const expandSceneCoMembers = `-- name: ExpandSceneCoMembers :many
SELECT DISTINCT FP.id, FP.hash
FROM scene_fingerprints SFP
JOIN fingerprints FP ON FP.id = SFP.fingerprint_id
WHERE SFP.scene_id = ANY($1::UUID[])
  AND FP.algorithm = 'PHASH'
`

type ExpandSceneCoMembersRow struct {
	ID   int   `db:"id" json:"id"`
	Hash int64 `db:"hash" json:"hash"`
}

func (q *Queries) ExpandSceneCoMembers(ctx context.Context, sceneIds []uuid.UUID) ([]ExpandSceneCoMembersRow, error) {
	rows, err := q.db.Query(ctx, expandSceneCoMembers, sceneIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpandSceneCoMembersRow{}
	for rows.Next() {
		var i ExpandSceneCoMembersRow
		if err := rows.Scan(&i.ID, &i.Hash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllFingerprints = `-- name: GetAllFingerprints :many
SELECT
    SFP.scene_id,
    FP.hash,
    FP.algorithm,
    mode() WITHIN GROUP (ORDER BY SFP.duration)::INTEGER as duration,
    COUNT(CASE WHEN SFP.vote = 1 THEN 1 END) as submissions,
    COUNT(CASE WHEN SFP.vote = -1 THEN 1 END) as reports,
    SUM(SFP.vote) as net_submissions,
    MIN(SFP.created_at)::TIMESTAMP as created_at,
    MAX(SFP.created_at)::TIMESTAMP as updated_at,
    bool_or(SFP.user_id = $1 AND SFP.vote = 1) as user_submitted,
    bool_or(SFP.user_id = $1 AND SFP.vote = -1) as user_reported
FROM scene_fingerprints SFP
JOIN fingerprints FP ON SFP.fingerprint_id = FP.id
WHERE SFP.scene_id = ANY($2::UUID[])
  AND ($3::uuid IS NULL OR SFP.user_id = $3)
GROUP BY SFP.scene_id, FP.algorithm, FP.hash
ORDER BY net_submissions DESC
`

type GetAllFingerprintsParams struct {
	CurrentUserID uuid.UUID     `db:"current_user_id" json:"current_user_id"`
	SceneIds      []uuid.UUID   `db:"scene_ids" json:"scene_ids"`
	FilterUserID  uuid.NullUUID `db:"filter_user_id" json:"filter_user_id"`
}

type GetAllFingerprintsRow struct {
	SceneID        uuid.UUID `db:"scene_id" json:"scene_id"`
	Hash           int64     `db:"hash" json:"hash"`
	Algorithm      string    `db:"algorithm" json:"algorithm"`
	Duration       int       `db:"duration" json:"duration"`
	Submissions    int64     `db:"submissions" json:"submissions"`
	Reports        int64     `db:"reports" json:"reports"`
	NetSubmissions int64     `db:"net_submissions" json:"net_submissions"`
	CreatedAt      time.Time `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time `db:"updated_at" json:"updated_at"`
	UserSubmitted  bool      `db:"user_submitted" json:"user_submitted"`
	UserReported   bool      `db:"user_reported" json:"user_reported"`
}

// Get all fingerprints for multiple scenes with aggregated vote data
// When onlySubmitted is true, pass the actual user ID, when false pass NULL
func (q *Queries) GetAllFingerprints(ctx context.Context, arg GetAllFingerprintsParams) ([]GetAllFingerprintsRow, error) {
	rows, err := q.db.Query(ctx, getAllFingerprints, arg.CurrentUserID, arg.SceneIds, arg.FilterUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllFingerprintsRow{}
	for rows.Next() {
		var i GetAllFingerprintsRow
		if err := rows.Scan(
			&i.SceneID,
			&i.Hash,
			&i.Algorithm,
			&i.Duration,
			&i.Submissions,
			&i.Reports,
			&i.NetSubmissions,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserSubmitted,
			&i.UserReported,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllSceneFingerprints = `-- name: GetAllSceneFingerprints :many
SELECT f.algorithm, f.hash, sf.duration, sf.created_at, sf.user_id
FROM scene_fingerprints sf
JOIN fingerprints f ON sf.fingerprint_id = f.id
WHERE sf.scene_id = $1
ORDER BY f.algorithm, sf.created_at
`

type GetAllSceneFingerprintsRow struct {
	Algorithm string    `db:"algorithm" json:"algorithm"`
	Hash      int64     `db:"hash" json:"hash"`
	Duration  int       `db:"duration" json:"duration"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetAllSceneFingerprints(ctx context.Context, sceneID uuid.UUID) ([]GetAllSceneFingerprintsRow, error) {
	rows, err := q.db.Query(ctx, getAllSceneFingerprints, sceneID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllSceneFingerprintsRow{}
	for rows.Next() {
		var i GetAllSceneFingerprintsRow
		if err := rows.Scan(
			&i.Algorithm,
			&i.Hash,
			&i.Duration,
			&i.CreatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFingerprint = `-- name: GetFingerprint :one
SELECT id, algorithm, hash FROM fingerprints WHERE hash = $1 AND algorithm = $2
`

type GetFingerprintParams struct {
	Hash      int64  `db:"hash" json:"hash"`
	Algorithm string `db:"algorithm" json:"algorithm"`
}

func (q *Queries) GetFingerprint(ctx context.Context, arg GetFingerprintParams) (Fingerprint, error) {
	row := q.db.QueryRow(ctx, getFingerprint, arg.Hash, arg.Algorithm)
	var i Fingerprint
	err := row.Scan(&i.ID, &i.Algorithm, &i.Hash)
	return i, err
}

const getSceneFingerprintScenes = `-- name: GetSceneFingerprintScenes :many
SELECT fingerprint_id, scene_id
FROM scene_fingerprints
WHERE fingerprint_id = ANY($1::INT[])
`

type GetSceneFingerprintScenesRow struct {
	FingerprintID int       `db:"fingerprint_id" json:"fingerprint_id"`
	SceneID       uuid.UUID `db:"scene_id" json:"scene_id"`
}

func (q *Queries) GetSceneFingerprintScenes(ctx context.Context, fingerprintIds []int) ([]GetSceneFingerprintScenesRow, error) {
	rows, err := q.db.Query(ctx, getSceneFingerprintScenes, fingerprintIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSceneFingerprintScenesRow{}
	for rows.Next() {
		var i GetSceneFingerprintScenesRow
		if err := rows.Scan(&i.FingerprintID, &i.SceneID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScenePhashSeeds = `-- name: GetScenePhashSeeds :many
SELECT DISTINCT FP.id, FP.hash
FROM scene_fingerprints SFP
JOIN fingerprints FP ON FP.id = SFP.fingerprint_id
WHERE SFP.scene_id = $1
  AND FP.algorithm = 'PHASH'
`

type GetScenePhashSeedsRow struct {
	ID   int   `db:"id" json:"id"`
	Hash int64 `db:"hash" json:"hash"`
}

func (q *Queries) GetScenePhashSeeds(ctx context.Context, sceneID uuid.UUID) ([]GetScenePhashSeedsRow, error) {
	rows, err := q.db.Query(ctx, getScenePhashSeeds, sceneID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetScenePhashSeedsRow{}
	for rows.Next() {
		var i GetScenePhashSeedsRow
		if err := rows.Scan(&i.ID, &i.Hash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadClusterFingerprints = `-- name: LoadClusterFingerprints :many
SELECT id, hash
FROM fingerprints
WHERE id = ANY($1::INT[])
`

type LoadClusterFingerprintsRow struct {
	ID   int   `db:"id" json:"id"`
	Hash int64 `db:"hash" json:"hash"`
}

func (q *Queries) LoadClusterFingerprints(ctx context.Context, fingerprintIds []int) ([]LoadClusterFingerprintsRow, error) {
	rows, err := q.db.Query(ctx, loadClusterFingerprints, fingerprintIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoadClusterFingerprintsRow{}
	for rows.Next() {
		var i LoadClusterFingerprintsRow
		if err := rows.Scan(&i.ID, &i.Hash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadClusterSubmissions = `-- name: LoadClusterSubmissions :many
SELECT
    fingerprint_id,
    scene_id,
    SUM(submissions)::INTEGER AS submissions,
    SUM(reports)::INTEGER AS reports,
    ARRAY_AGG(duration ORDER BY duration)::INTEGER[] AS durations,
    ARRAY_AGG(submissions ORDER BY duration)::INTEGER[] AS duration_submissions
FROM (
    SELECT
        SFP.fingerprint_id,
        SFP.scene_id,
        SFP.duration,
        COUNT(*) FILTER (WHERE SFP.vote = 1)::INTEGER AS submissions,
        COUNT(*) FILTER (WHERE SFP.vote = -1)::INTEGER AS reports
    FROM scene_fingerprints SFP
    WHERE SFP.fingerprint_id = ANY($1::INT[])
    GROUP BY SFP.fingerprint_id, SFP.scene_id, SFP.duration
) per_dur
GROUP BY fingerprint_id, scene_id
`

type LoadClusterSubmissionsRow struct {
	FingerprintID       int       `db:"fingerprint_id" json:"fingerprint_id"`
	SceneID             uuid.UUID `db:"scene_id" json:"scene_id"`
	Submissions         int       `db:"submissions" json:"submissions"`
	Reports             int       `db:"reports" json:"reports"`
	Durations           []int     `db:"durations" json:"durations"`
	DurationSubmissions []int     `db:"duration_submissions" json:"duration_submissions"`
}

func (q *Queries) LoadClusterSubmissions(ctx context.Context, fingerprintIds []int) ([]LoadClusterSubmissionsRow, error) {
	rows, err := q.db.Query(ctx, loadClusterSubmissions, fingerprintIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoadClusterSubmissionsRow{}
	for rows.Next() {
		var i LoadClusterSubmissionsRow
		if err := rows.Scan(
			&i.FingerprintID,
			&i.SceneID,
			&i.Submissions,
			&i.Reports,
			&i.Durations,
			&i.DurationSubmissions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadLinkedOshashSubmissions = `-- name: LoadLinkedOshashSubmissions :many
SELECT
    OS_SFP.fingerprint_id AS oshash_fingerprint_id,
    PH_SFP.fingerprint_id AS phash_fingerprint_id,
    OS_SFP.scene_id,
    OS_SFP.user_id,
    OS_SFP.created_at,
    OS_SFP.vote,
    OS_SFP.duration
FROM scene_fingerprints OS_SFP
JOIN fingerprints OS_FP ON OS_FP.id = OS_SFP.fingerprint_id AND OS_FP.algorithm = 'OSHASH'
JOIN scene_fingerprints PH_SFP
    ON PH_SFP.scene_id = OS_SFP.scene_id
    AND PH_SFP.user_id = OS_SFP.user_id
    AND ABS(EXTRACT(EPOCH FROM (OS_SFP.created_at - PH_SFP.created_at))) <= 60
WHERE PH_SFP.fingerprint_id = ANY($1::INT[])
`

type LoadLinkedOshashSubmissionsRow struct {
	OshashFingerprintID int       `db:"oshash_fingerprint_id" json:"oshash_fingerprint_id"`
	PhashFingerprintID  int       `db:"phash_fingerprint_id" json:"phash_fingerprint_id"`
	SceneID             uuid.UUID `db:"scene_id" json:"scene_id"`
	UserID              uuid.UUID `db:"user_id" json:"user_id"`
	CreatedAt           time.Time `db:"created_at" json:"created_at"`
	Vote                int16     `db:"vote" json:"vote"`
	Duration            int       `db:"duration" json:"duration"`
}

func (q *Queries) LoadLinkedOshashSubmissions(ctx context.Context, phashFingerprintIds []int) ([]LoadLinkedOshashSubmissionsRow, error) {
	rows, err := q.db.Query(ctx, loadLinkedOshashSubmissions, phashFingerprintIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoadLinkedOshashSubmissionsRow{}
	for rows.Next() {
		var i LoadLinkedOshashSubmissionsRow
		if err := rows.Scan(
			&i.OshashFingerprintID,
			&i.PhashFingerprintID,
			&i.SceneID,
			&i.UserID,
			&i.CreatedAt,
			&i.Vote,
			&i.Duration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveSceneFingerprintSubmissions = `-- name: MoveSceneFingerprintSubmissions :execrows
UPDATE scene_fingerprints SFP
SET scene_id = $1
FROM fingerprints FP
WHERE SFP.fingerprint_id = FP.id
  AND FP.hash = $2
  AND FP.algorithm = $3
  AND SFP.scene_id = $4
`

type MoveSceneFingerprintSubmissionsParams struct {
	TargetSceneID uuid.UUID `db:"target_scene_id" json:"target_scene_id"`
	Hash          int64     `db:"hash" json:"hash"`
	Algorithm     string    `db:"algorithm" json:"algorithm"`
	SourceSceneID uuid.UUID `db:"source_scene_id" json:"source_scene_id"`
}

func (q *Queries) MoveSceneFingerprintSubmissions(ctx context.Context, arg MoveSceneFingerprintSubmissionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, moveSceneFingerprintSubmissions,
		arg.TargetSceneID,
		arg.Hash,
		arg.Algorithm,
		arg.SourceSceneID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const submittedHashExists = `-- name: SubmittedHashExists :one
SELECT EXISTS(
		SELECT
			1
		FROM scene_fingerprints f
		JOIN fingerprints fp ON f.fingerprint_id = fp.id
		WHERE f.scene_id = $1 AND fp.hash = $2 AND fp.algorithm = $3 AND f.vote = 1
) AS exists
`

type SubmittedHashExistsParams struct {
	SceneID   uuid.UUID `db:"scene_id" json:"scene_id"`
	Hash      int64     `db:"hash" json:"hash"`
	Algorithm string    `db:"algorithm" json:"algorithm"`
}

func (q *Queries) SubmittedHashExists(ctx context.Context, arg SubmittedHashExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, submittedHashExists, arg.SceneID, arg.Hash, arg.Algorithm)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
