// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: image_audit.sql

package queries

import (
	"context"
	"encoding/json"

	"github.com/gofrs/uuid"
)

const createImageAudit = `-- name: CreateImageAudit :one

INSERT INTO image_audit (id, action, user_id, image_id, data, created_at)
VALUES ($1, $2, $3, $4, $5, NOW())
RETURNING id, action, user_id, image_id, data, created_at
`

type CreateImageAuditParams struct {
	ID      uuid.UUID       `db:"id" json:"id"`
	Action  string          `db:"action" json:"action"`
	UserID  uuid.NullUUID   `db:"user_id" json:"user_id"`
	ImageID uuid.UUID       `db:"image_id" json:"image_id"`
	Data    json.RawMessage `db:"data" json:"data"`
}

// Image audit queries
func (q *Queries) CreateImageAudit(ctx context.Context, arg CreateImageAuditParams) (ImageAudit, error) {
	row := q.db.QueryRow(ctx, createImageAudit,
		arg.ID,
		arg.Action,
		arg.UserID,
		arg.ImageID,
		arg.Data,
	)
	var i ImageAudit
	err := row.Scan(
		&i.ID,
		&i.Action,
		&i.UserID,
		&i.ImageID,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredImageAudits = `-- name: DeleteExpiredImageAudits :exec
DELETE FROM image_audit
WHERE created_at < NOW() - INTERVAL '1 day' * $1
`

func (q *Queries) DeleteExpiredImageAudits(ctx context.Context, dollar_1 interface{}) error {
	_, err := q.db.Exec(ctx, deleteExpiredImageAudits, dollar_1)
	return err
}

const getImageAudits = `-- name: GetImageAudits :many
SELECT id, action, user_id, image_id, data, created_at FROM image_audit
WHERE image_id = $1
  AND ($2::text IS NULL OR action = $2)
ORDER BY created_at DESC, id DESC
`

type GetImageAuditsParams struct {
	ImageID uuid.UUID `db:"image_id" json:"image_id"`
	Action  *string   `db:"action" json:"action"`
}

// One image's trail, newest first. The optional action narrowing is what
// the revert uses to find the categorization state to restore.
func (q *Queries) GetImageAudits(ctx context.Context, arg GetImageAuditsParams) ([]ImageAudit, error) {
	rows, err := q.db.Query(ctx, getImageAudits, arg.ImageID, arg.Action)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImageAudit{}
	for rows.Next() {
		var i ImageAudit
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.UserID,
			&i.ImageID,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
