// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: image.sql

package queries

import (
	"context"

	"github.com/gofrs/uuid"
)

const createImage = `-- name: CreateImage :one

INSERT INTO images (id, url, width, height, checksum)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, url, width, height, checksum
`

type CreateImageParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	Url      *string   `db:"url" json:"url"`
	Width    int       `db:"width" json:"width"`
	Height   int       `db:"height" json:"height"`
	Checksum string    `db:"checksum" json:"checksum"`
}

// Image queries
func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) (Image, error) {
	row := q.db.QueryRow(ctx, createImage,
		arg.ID,
		arg.Url,
		arg.Width,
		arg.Height,
		arg.Checksum,
	)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Width,
		&i.Height,
		&i.Checksum,
	)
	return i, err
}

const deleteImage = `-- name: DeleteImage :exec
DELETE FROM images WHERE id = $1
`

func (q *Queries) DeleteImage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteImage, id)
	return err
}

const findImage = `-- name: FindImage :one
SELECT id, url, width, height, checksum FROM images WHERE id = $1
`

func (q *Queries) FindImage(ctx context.Context, id uuid.UUID) (Image, error) {
	row := q.db.QueryRow(ctx, findImage, id)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Width,
		&i.Height,
		&i.Checksum,
	)
	return i, err
}

const findImageByChecksum = `-- name: FindImageByChecksum :one
SELECT id, url, width, height, checksum FROM images WHERE checksum = $1
`

func (q *Queries) FindImageByChecksum(ctx context.Context, checksum string) (Image, error) {
	row := q.db.QueryRow(ctx, findImageByChecksum, checksum)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Width,
		&i.Height,
		&i.Checksum,
	)
	return i, err
}

const findImageIdsByPerformerIds = `-- name: FindImageIdsByPerformerIds :many
SELECT performer_images.performer_id, performer_images.image_id
FROM performer_images
WHERE performer_images.performer_id = ANY($1::UUID[])
`

func (q *Queries) FindImageIdsByPerformerIds(ctx context.Context, dollar_1 []uuid.UUID) ([]PerformerImage, error) {
	rows, err := q.db.Query(ctx, findImageIdsByPerformerIds, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PerformerImage{}
	for rows.Next() {
		var i PerformerImage
		if err := rows.Scan(&i.PerformerID, &i.ImageID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findImageIdsBySceneIds = `-- name: FindImageIdsBySceneIds :many
SELECT scene_images.scene_id, scene_images.image_id
FROM scene_images
WHERE scene_images.scene_id = ANY($1::UUID[])
`

func (q *Queries) FindImageIdsBySceneIds(ctx context.Context, dollar_1 []uuid.UUID) ([]SceneImage, error) {
	rows, err := q.db.Query(ctx, findImageIdsBySceneIds, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SceneImage{}
	for rows.Next() {
		var i SceneImage
		if err := rows.Scan(&i.SceneID, &i.ImageID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findImageIdsByStudioIds = `-- name: FindImageIdsByStudioIds :many
SELECT studio_images.studio_id, studio_images.image_id
FROM studio_images
WHERE studio_images.studio_id = ANY($1::UUID[])
`

func (q *Queries) FindImageIdsByStudioIds(ctx context.Context, dollar_1 []uuid.UUID) ([]StudioImage, error) {
	rows, err := q.db.Query(ctx, findImageIdsByStudioIds, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StudioImage{}
	for rows.Next() {
		var i StudioImage
		if err := rows.Scan(&i.StudioID, &i.ImageID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findImagesByIds = `-- name: FindImagesByIds :many
SELECT id, url, width, height, checksum FROM images WHERE id = ANY($1::UUID[])
`

func (q *Queries) FindImagesByIds(ctx context.Context, dollar_1 []uuid.UUID) ([]Image, error) {
	rows, err := q.db.Query(ctx, findImagesByIds, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Image{}
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Width,
			&i.Height,
			&i.Checksum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findImagesBySceneID = `-- name: FindImagesBySceneID :many
SELECT images.id, images.url, images.width, images.height, images.checksum FROM images
LEFT JOIN scene_images as scenes_join on scenes_join.image_id = images.id
LEFT JOIN scenes on scenes_join.scene_id = scenes.id
WHERE scenes.id = $1
`

func (q *Queries) FindImagesBySceneID(ctx context.Context, id uuid.UUID) ([]Image, error) {
	rows, err := q.db.Query(ctx, findImagesBySceneID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Image{}
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Width,
			&i.Height,
			&i.Checksum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findImagesByStudioID = `-- name: FindImagesByStudioID :many
SELECT images.id, images.url, images.width, images.height, images.checksum FROM images
LEFT JOIN studio_images as studios_join on studios_join.image_id = images.id
LEFT JOIN studios on studios_join.studio_id = studios.id
WHERE studios.id = $1
`

func (q *Queries) FindImagesByStudioID(ctx context.Context, id uuid.UUID) ([]Image, error) {
	rows, err := q.db.Query(ctx, findImagesByStudioID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Image{}
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Width,
			&i.Height,
			&i.Checksum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findUnusedImages = `-- name: FindUnusedImages :many
SELECT images.id, images.url, images.width, images.height, images.checksum from images
LEFT JOIN scene_images ON scene_images.image_id = images.id
LEFT JOIN performer_images ON performer_images.image_id = images.id
LEFT JOIN studio_images ON studio_images.image_id = images.id
LEFT JOIN (
    SELECT (jsonb_array_elements(data#>'{new_data,added_images}')->>0)::uuid AS image_id
    FROM edits
    WHERE status = 'PENDING'
) edit_images ON edit_images.image_id = images.id
LEFT JOIN (
    SELECT id, (data->>'image')::uuid AS image_id
    FROM drafts
) drafts ON images.id = drafts.image_id
WHERE scene_images.scene_id IS NULL
AND performer_images.performer_id IS NULL
AND studio_images.studio_id IS NULL
AND edit_images.image_id IS NULL
AND drafts.id IS NULL
LIMIT 1000
`

func (q *Queries) FindUnusedImages(ctx context.Context) ([]Image, error) {
	rows, err := q.db.Query(ctx, findUnusedImages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Image{}
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Width,
			&i.Height,
			&i.Checksum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isImageUnused = `-- name: IsImageUnused :one
SELECT COUNT(*) > 0 AS unused from images
LEFT JOIN scene_images ON scene_images.image_id = images.id
LEFT JOIN performer_images ON performer_images.image_id = images.id
LEFT JOIN studio_images ON studio_images.image_id = images.id
LEFT JOIN (
    SELECT (jsonb_array_elements(data#>'{new_data,added_images}')->>0)::uuid AS image_id
    FROM edits
    WHERE status = 'PENDING'
) edit_images ON edit_images.image_id = images.id
LEFT JOIN (
    SELECT id, (data->>'image')::uuid AS image_id
    FROM drafts
) drafts ON images.id = drafts.image_id
WHERE images.id = $1
AND scene_images.scene_id IS NULL
AND performer_images.performer_id IS NULL
AND studio_images.studio_id IS NULL
AND edit_images.image_id IS NULL
AND drafts.id IS NULL
`

func (q *Queries) IsImageUnused(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isImageUnused, id)
	var unused bool
	err := row.Scan(&unused)
	return unused, err
}
