// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: image_type.sql

package queries

import (
	"context"

	"github.com/gofrs/uuid"
)

type CreatePerformerImageTypesParams struct {
	PerformerID uuid.UUID `db:"performer_id" json:"performer_id"`
	ImageID     uuid.UUID `db:"image_id" json:"image_id"`
	TypeKey     string    `db:"type_key" json:"type_key"`
}

type CreateUserImageTypeGroupPreferencesParams struct {
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
	GroupKey  string    `db:"group_key" json:"group_key"`
	SortOrder int       `db:"sort_order" json:"sort_order"`
}

type CreateUserImageTypePreferencesParams struct {
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
	TypeKey   string    `db:"type_key" json:"type_key"`
	SortOrder int       `db:"sort_order" json:"sort_order"`
}

const deletePerformerImageTypes = `-- name: DeletePerformerImageTypes :exec
DELETE FROM performer_image_types WHERE performer_id = $1
`

func (q *Queries) DeletePerformerImageTypes(ctx context.Context, performerID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePerformerImageTypes, performerID)
	return err
}

const deleteUserImageTypeGroupPreferences = `-- name: DeleteUserImageTypeGroupPreferences :exec
DELETE FROM user_image_type_group_preferences WHERE user_id = $1
`

func (q *Queries) DeleteUserImageTypeGroupPreferences(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserImageTypeGroupPreferences, userID)
	return err
}

const deleteUserImageTypePreferences = `-- name: DeleteUserImageTypePreferences :exec
DELETE FROM user_image_type_preferences WHERE user_id = $1
`

func (q *Queries) DeleteUserImageTypePreferences(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserImageTypePreferences, userID)
	return err
}

const findImageDatesByPerformerIds = `-- name: FindImageDatesByPerformerIds :many
SELECT performer_id, image_id, date
FROM performer_images
WHERE performer_id = ANY($1::UUID[])
`

func (q *Queries) FindImageDatesByPerformerIds(ctx context.Context, performerIds []uuid.UUID) ([]PerformerImage, error) {
	rows, err := q.db.Query(ctx, findImageDatesByPerformerIds, performerIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PerformerImage{}
	for rows.Next() {
		var i PerformerImage
		if err := rows.Scan(&i.PerformerID, &i.ImageID, &i.Date); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findImageTypesByPerformerIds = `-- name: FindImageTypesByPerformerIds :many
SELECT pit.performer_id, pit.image_id, pit.type_key
FROM performer_image_types pit
JOIN image_types it ON it.key = pit.type_key
JOIN image_type_groups itg ON itg.key = it.group_key
WHERE pit.performer_id = ANY($1::UUID[])
ORDER BY itg.sort_order ASC, it.sort_order ASC
`

// Ordered by the vocabulary rather than alphabetically, so an image's labels
// read in the same priority order the admin set.
func (q *Queries) FindImageTypesByPerformerIds(ctx context.Context, performerIds []uuid.UUID) ([]PerformerImageType, error) {
	rows, err := q.db.Query(ctx, findImageTypesByPerformerIds, performerIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PerformerImageType{}
	for rows.Next() {
		var i PerformerImageType
		if err := rows.Scan(&i.PerformerID, &i.ImageID, &i.TypeKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllImageTypeConflicts = `-- name: GetAllImageTypeConflicts :many
SELECT type_key, conflicts_with_key FROM image_type_conflicts
`

func (q *Queries) GetAllImageTypeConflicts(ctx context.Context) ([]ImageTypeConflict, error) {
	rows, err := q.db.Query(ctx, getAllImageTypeConflicts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImageTypeConflict{}
	for rows.Next() {
		var i ImageTypeConflict
		if err := rows.Scan(&i.TypeKey, &i.ConflictsWithKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllImageTypeGroups = `-- name: GetAllImageTypeGroups :many

SELECT key, name, description, sort_order, exclusive, enabled FROM image_type_groups ORDER BY sort_order ASC
`

// Image type vocabulary queries.
//
// The vocabulary is seeded by migration and only sort_order is writable at
// runtime, so there is no create or delete here.
func (q *Queries) GetAllImageTypeGroups(ctx context.Context) ([]ImageTypeGroup, error) {
	rows, err := q.db.Query(ctx, getAllImageTypeGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImageTypeGroup{}
	for rows.Next() {
		var i ImageTypeGroup
		if err := rows.Scan(
			&i.Key,
			&i.Name,
			&i.Description,
			&i.SortOrder,
			&i.Exclusive,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllImageTypes = `-- name: GetAllImageTypes :many
SELECT key, name, description, group_key, sort_order, valid_types, enabled FROM image_types ORDER BY group_key ASC, sort_order ASC
`

func (q *Queries) GetAllImageTypes(ctx context.Context) ([]ImageType, error) {
	rows, err := q.db.Query(ctx, getAllImageTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImageType{}
	for rows.Next() {
		var i ImageType
		if err := rows.Scan(
			&i.Key,
			&i.Name,
			&i.Description,
			&i.GroupKey,
			&i.SortOrder,
			&i.ValidTypes,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getImageTypesByTarget = `-- name: GetImageTypesByTarget :many
SELECT key, name, description, group_key, sort_order, valid_types, enabled FROM image_types
WHERE $1::text = ANY(valid_types)
ORDER BY group_key ASC, sort_order ASC
`

// Types valid for one entity kind. $1 is a bare target name, e.g. 'PERFORMER'.
func (q *Queries) GetImageTypesByTarget(ctx context.Context, target string) ([]ImageType, error) {
	rows, err := q.db.Query(ctx, getImageTypesByTarget, target)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImageType{}
	for rows.Next() {
		var i ImageType
		if err := rows.Scan(
			&i.Key,
			&i.Name,
			&i.Description,
			&i.GroupKey,
			&i.SortOrder,
			&i.ValidTypes,
			&i.Enabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserImageTypeGroupPreferences = `-- name: GetUserImageTypeGroupPreferences :many
SELECT group_key FROM user_image_type_group_preferences
WHERE user_id = $1
ORDER BY sort_order ASC
`

func (q *Queries) GetUserImageTypeGroupPreferences(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserImageTypeGroupPreferences, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var group_key string
		if err := rows.Scan(&group_key); err != nil {
			return nil, err
		}
		items = append(items, group_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserImageTypePreferences = `-- name: GetUserImageTypePreferences :many

SELECT type_key FROM user_image_type_preferences
WHERE user_id = $1
ORDER BY sort_order ASC
`

// User preferences
func (q *Queries) GetUserImageTypePreferences(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserImageTypePreferences, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var type_key string
		if err := rows.Scan(&type_key); err != nil {
			return nil, err
		}
		items = append(items, type_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setImageTypeGroupsEnabled = `-- name: SetImageTypeGroupsEnabled :exec

UPDATE image_type_groups SET enabled = NOT ("key" = ANY(COALESCE($1::text[], '{}')))
`

// Enabling
// Takes the complete set of disabled keys, so a group absent from the list is
// enabled. A type added to the vocabulary later is therefore on by default,
// which an "enabled set" would have silently reversed.
//
// COALESCE because an array arriving as SQL NULL would set enabled = NULL on
// every row rather than enabling them: NOT (key = ANY(NULL)) is NULL, not true.
func (q *Queries) SetImageTypeGroupsEnabled(ctx context.Context, disabled []string) error {
	_, err := q.db.Exec(ctx, setImageTypeGroupsEnabled, disabled)
	return err
}

const setImageTypesEnabled = `-- name: SetImageTypesEnabled :exec
UPDATE image_types SET enabled = NOT ("key" = ANY(COALESCE($1::text[], '{}')))
`

func (q *Queries) SetImageTypesEnabled(ctx context.Context, disabled []string) error {
	_, err := q.db.Exec(ctx, setImageTypesEnabled, disabled)
	return err
}

const updateImageTypeGroupSortOrder = `-- name: UpdateImageTypeGroupSortOrder :exec
UPDATE image_type_groups SET sort_order = $2 WHERE key = $1
`

type UpdateImageTypeGroupSortOrderParams struct {
	Key       string `db:"key" json:"key"`
	SortOrder int    `db:"sort_order" json:"sort_order"`
}

// Both sort_order unique constraints are deferred, so a reorder can be one
// UPDATE per row without contriving a collision-free intermediate permutation.
func (q *Queries) UpdateImageTypeGroupSortOrder(ctx context.Context, arg UpdateImageTypeGroupSortOrderParams) error {
	_, err := q.db.Exec(ctx, updateImageTypeGroupSortOrder, arg.Key, arg.SortOrder)
	return err
}

const updateImageTypeSortOrder = `-- name: UpdateImageTypeSortOrder :exec
UPDATE image_types SET sort_order = $2 WHERE key = $1
`

type UpdateImageTypeSortOrderParams struct {
	Key       string `db:"key" json:"key"`
	SortOrder int    `db:"sort_order" json:"sort_order"`
}

func (q *Queries) UpdateImageTypeSortOrder(ctx context.Context, arg UpdateImageTypeSortOrderParams) error {
	_, err := q.db.Exec(ctx, updateImageTypeSortOrder, arg.Key, arg.SortOrder)
	return err
}
