// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: image.sql

package queries

import (
	"context"
	"time"

	"github.com/gofrs/uuid"
)

const createImage = `-- name: CreateImage :one

INSERT INTO images (id, url, width, height, checksum, date, organized, categorized_at, categorized_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, url, width, height, checksum, date, organized, categorized_at, categorized_by
`

type CreateImageParams struct {
	ID            uuid.UUID     `db:"id" json:"id"`
	Url           *string       `db:"url" json:"url"`
	Width         int           `db:"width" json:"width"`
	Height        int           `db:"height" json:"height"`
	Checksum      string        `db:"checksum" json:"checksum"`
	Date          *string       `db:"date" json:"date"`
	Organized     bool          `db:"organized" json:"organized"`
	CategorizedAt *time.Time    `db:"categorized_at" json:"categorized_at"`
	CategorizedBy uuid.NullUUID `db:"categorized_by" json:"categorized_by"`
}

// Image queries
func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) (Image, error) {
	row := q.db.QueryRow(ctx, createImage,
		arg.ID,
		arg.Url,
		arg.Width,
		arg.Height,
		arg.Checksum,
		arg.Date,
		arg.Organized,
		arg.CategorizedAt,
		arg.CategorizedBy,
	)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Width,
		&i.Height,
		&i.Checksum,
		&i.Date,
		&i.Organized,
		&i.CategorizedAt,
		&i.CategorizedBy,
	)
	return i, err
}

const deleteImage = `-- name: DeleteImage :exec
DELETE FROM images WHERE id = $1
`

func (q *Queries) DeleteImage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteImage, id)
	return err
}

const findImage = `-- name: FindImage :one
SELECT id, url, width, height, checksum, date, organized, categorized_at, categorized_by FROM images WHERE id = $1
`

func (q *Queries) FindImage(ctx context.Context, id uuid.UUID) (Image, error) {
	row := q.db.QueryRow(ctx, findImage, id)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Width,
		&i.Height,
		&i.Checksum,
		&i.Date,
		&i.Organized,
		&i.CategorizedAt,
		&i.CategorizedBy,
	)
	return i, err
}

const findImageByChecksum = `-- name: FindImageByChecksum :one
SELECT id, url, width, height, checksum, date, organized, categorized_at, categorized_by FROM images WHERE checksum = $1
`

func (q *Queries) FindImageByChecksum(ctx context.Context, checksum string) (Image, error) {
	row := q.db.QueryRow(ctx, findImageByChecksum, checksum)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Width,
		&i.Height,
		&i.Checksum,
		&i.Date,
		&i.Organized,
		&i.CategorizedAt,
		&i.CategorizedBy,
	)
	return i, err
}

const findImageIdsByPerformerIds = `-- name: FindImageIdsByPerformerIds :many
SELECT performer_images.performer_id, performer_images.image_id
FROM performer_images
WHERE performer_images.performer_id = ANY($1::UUID[])
`

func (q *Queries) FindImageIdsByPerformerIds(ctx context.Context, dollar_1 []uuid.UUID) ([]PerformerImage, error) {
	rows, err := q.db.Query(ctx, findImageIdsByPerformerIds, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PerformerImage{}
	for rows.Next() {
		var i PerformerImage
		if err := rows.Scan(&i.PerformerID, &i.ImageID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findImageIdsBySceneIds = `-- name: FindImageIdsBySceneIds :many
SELECT scene_images.scene_id, scene_images.image_id
FROM scene_images
WHERE scene_images.scene_id = ANY($1::UUID[])
`

func (q *Queries) FindImageIdsBySceneIds(ctx context.Context, dollar_1 []uuid.UUID) ([]SceneImage, error) {
	rows, err := q.db.Query(ctx, findImageIdsBySceneIds, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SceneImage{}
	for rows.Next() {
		var i SceneImage
		if err := rows.Scan(&i.SceneID, &i.ImageID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findImageIdsByStudioIds = `-- name: FindImageIdsByStudioIds :many
SELECT studio_images.studio_id, studio_images.image_id
FROM studio_images
WHERE studio_images.studio_id = ANY($1::UUID[])
`

func (q *Queries) FindImageIdsByStudioIds(ctx context.Context, dollar_1 []uuid.UUID) ([]StudioImage, error) {
	rows, err := q.db.Query(ctx, findImageIdsByStudioIds, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StudioImage{}
	for rows.Next() {
		var i StudioImage
		if err := rows.Scan(&i.StudioID, &i.ImageID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findImagesByIds = `-- name: FindImagesByIds :many
SELECT id, url, width, height, checksum, date, organized, categorized_at, categorized_by FROM images WHERE id = ANY($1::UUID[])
`

func (q *Queries) FindImagesByIds(ctx context.Context, dollar_1 []uuid.UUID) ([]Image, error) {
	rows, err := q.db.Query(ctx, findImagesByIds, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Image{}
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Width,
			&i.Height,
			&i.Checksum,
			&i.Date,
			&i.Organized,
			&i.CategorizedAt,
			&i.CategorizedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findImagesBySceneID = `-- name: FindImagesBySceneID :many
SELECT images.id, images.url, images.width, images.height, images.checksum, images.date, images.organized, images.categorized_at, images.categorized_by FROM images
LEFT JOIN scene_images as scenes_join on scenes_join.image_id = images.id
LEFT JOIN scenes on scenes_join.scene_id = scenes.id
WHERE scenes.id = $1
`

func (q *Queries) FindImagesBySceneID(ctx context.Context, id uuid.UUID) ([]Image, error) {
	rows, err := q.db.Query(ctx, findImagesBySceneID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Image{}
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Width,
			&i.Height,
			&i.Checksum,
			&i.Date,
			&i.Organized,
			&i.CategorizedAt,
			&i.CategorizedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findImagesByStudioID = `-- name: FindImagesByStudioID :many
SELECT images.id, images.url, images.width, images.height, images.checksum, images.date, images.organized, images.categorized_at, images.categorized_by FROM images
LEFT JOIN studio_images as studios_join on studios_join.image_id = images.id
LEFT JOIN studios on studios_join.studio_id = studios.id
WHERE studios.id = $1
`

func (q *Queries) FindImagesByStudioID(ctx context.Context, id uuid.UUID) ([]Image, error) {
	rows, err := q.db.Query(ctx, findImagesByStudioID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Image{}
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Width,
			&i.Height,
			&i.Checksum,
			&i.Date,
			&i.Organized,
			&i.CategorizedAt,
			&i.CategorizedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findUnusedImages = `-- name: FindUnusedImages :many
SELECT images.id, images.url, images.width, images.height, images.checksum, images.date, images.organized, images.categorized_at, images.categorized_by from images
LEFT JOIN scene_images ON scene_images.image_id = images.id
LEFT JOIN performer_images ON performer_images.image_id = images.id
LEFT JOIN studio_images ON studio_images.image_id = images.id
LEFT JOIN (
    SELECT (jsonb_array_elements(data#>'{new_data,added_images}')->>0)::uuid AS image_id
    FROM edits
    WHERE status = 'PENDING'
) edit_images ON edit_images.image_id = images.id
LEFT JOIN (
    SELECT id, (data->>'image')::uuid AS image_id
    FROM drafts
) drafts ON images.id = drafts.image_id
WHERE scene_images.scene_id IS NULL
AND performer_images.performer_id IS NULL
AND studio_images.studio_id IS NULL
AND edit_images.image_id IS NULL
AND drafts.id IS NULL
LIMIT 1000
`

// The added_images path below has no COALESCE, and does not need one: a
// pending edit predating image types has no such key, and jsonb_array_elements
// is STRICT, so a set-returning function given NULL yields zero rows rather
// than erroring. Keep added_images a flat UUID array for the same reason.
func (q *Queries) FindUnusedImages(ctx context.Context) ([]Image, error) {
	rows, err := q.db.Query(ctx, findUnusedImages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Image{}
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Width,
			&i.Height,
			&i.Checksum,
			&i.Date,
			&i.Organized,
			&i.CategorizedAt,
			&i.CategorizedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnorganizedImageCount = `-- name: GetUnorganizedImageCount :one
SELECT COUNT(*) FROM images
WHERE images.organized = false AND images.categorized_at IS NOT NULL
AND EXISTS (
    SELECT 1 FROM performer_images
    WHERE performer_images.image_id = images.id
)
AND ($1::uuid IS NULL OR EXISTS (
    SELECT 1 FROM performer_images
    WHERE performer_images.image_id = images.id
    AND performer_images.performer_id = $1
))
AND ($2::uuid IS NULL OR images.categorized_by = $2)
`

type GetUnorganizedImageCountParams struct {
	PerformerID uuid.NullUUID `db:"performer_id" json:"performer_id"`
	UserID      uuid.NullUUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetUnorganizedImageCount(ctx context.Context, arg GetUnorganizedImageCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, getUnorganizedImageCount, arg.PerformerID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const isImageUnused = `-- name: IsImageUnused :one
SELECT COUNT(*) > 0 AS unused from images
LEFT JOIN scene_images ON scene_images.image_id = images.id
LEFT JOIN performer_images ON performer_images.image_id = images.id
LEFT JOIN studio_images ON studio_images.image_id = images.id
LEFT JOIN (
    SELECT (jsonb_array_elements(data#>'{new_data,added_images}')->>0)::uuid AS image_id
    FROM edits
    WHERE status = 'PENDING'
) edit_images ON edit_images.image_id = images.id
LEFT JOIN (
    SELECT id, (data->>'image')::uuid AS image_id
    FROM drafts
) drafts ON images.id = drafts.image_id
WHERE images.id = $1
AND scene_images.scene_id IS NULL
AND performer_images.performer_id IS NULL
AND studio_images.studio_id IS NULL
AND edit_images.image_id IS NULL
AND drafts.id IS NULL
`

func (q *Queries) IsImageUnused(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isImageUnused, id)
	var unused bool
	err := row.Scan(&unused)
	return unused, err
}

const queryUnorganizedImages = `-- name: QueryUnorganizedImages :many
SELECT images.id, images.url, images.width, images.height, images.checksum, images.date, images.organized, images.categorized_at, images.categorized_by, performer.id AS performer_id, performer.name AS performer_name
FROM images
JOIN LATERAL (
    SELECT performers.id, performers.name
    FROM performer_images
    JOIN performers ON performers.id = performer_images.performer_id
    WHERE performer_images.image_id = images.id
    LIMIT 1
) performer ON true
WHERE images.organized = false AND images.categorized_at IS NOT NULL
AND ($3::uuid IS NULL OR EXISTS (
    SELECT 1 FROM performer_images
    WHERE performer_images.image_id = images.id
    AND performer_images.performer_id = $3
))
AND ($4::uuid IS NULL OR images.categorized_by = $4)
ORDER BY images.categorized_at DESC, images.id
LIMIT $1 OFFSET $2
`

type QueryUnorganizedImagesParams struct {
	Limit       int32         `db:"limit" json:"limit"`
	Offset      int32         `db:"offset" json:"offset"`
	PerformerID uuid.NullUUID `db:"performer_id" json:"performer_id"`
	UserID      uuid.NullUUID `db:"user_id" json:"user_id"`
}

type QueryUnorganizedImagesRow struct {
	Image         Image     `db:"image" json:"image"`
	PerformerID   uuid.UUID `db:"performer_id" json:"performer_id"`
	PerformerName string    `db:"performer_name" json:"performer_name"`
}

// The moderator review feed: every attached image a contributor has
// categorized that no moderator has signed off on yet, newest categorization
// first so fresh work surfaces. Restricted to images on a performer: an
// unattached categorized image is riding a pending edit that may yet be voted
// down, and reviewing it early would be wasted work. The owning performer
// rides along because a bare thumbnail tells a reviewer nothing.
// LATERAL with LIMIT 1 rather than a plain join: a checksum-deduplicated
// image can in principle be attached to more than one performer, and a
// fanned-out join would duplicate feed rows and desynchronize the count.
// The optional narrowing to one contributor's work, keyed on who categorized
// the image last: the fast answer to "what has this user touched?"
func (q *Queries) QueryUnorganizedImages(ctx context.Context, arg QueryUnorganizedImagesParams) ([]QueryUnorganizedImagesRow, error) {
	rows, err := q.db.Query(ctx, queryUnorganizedImages,
		arg.Limit,
		arg.Offset,
		arg.PerformerID,
		arg.UserID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QueryUnorganizedImagesRow{}
	for rows.Next() {
		var i QueryUnorganizedImagesRow
		if err := rows.Scan(
			&i.Image.ID,
			&i.Image.Url,
			&i.Image.Width,
			&i.Image.Height,
			&i.Image.Checksum,
			&i.Image.Date,
			&i.Image.Organized,
			&i.Image.CategorizedAt,
			&i.Image.CategorizedBy,
			&i.PerformerID,
			&i.PerformerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setImageOrganized = `-- name: SetImageOrganized :one
UPDATE images SET organized = $2 WHERE id = $1
RETURNING id, url, width, height, checksum, date, organized, categorized_at, categorized_by
`

type SetImageOrganizedParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	Organized bool      `db:"organized" json:"organized"`
}

func (q *Queries) SetImageOrganized(ctx context.Context, arg SetImageOrganizedParams) (Image, error) {
	row := q.db.QueryRow(ctx, setImageOrganized, arg.ID, arg.Organized)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Width,
		&i.Height,
		&i.Checksum,
		&i.Date,
		&i.Organized,
		&i.CategorizedAt,
		&i.CategorizedBy,
	)
	return i, err
}

const updateImage = `-- name: UpdateImage :one
UPDATE images SET url = $2, date = $3, categorized_at = $4, categorized_by = $5 WHERE id = $1
RETURNING id, url, width, height, checksum, date, organized, categorized_at, categorized_by
`

type UpdateImageParams struct {
	ID            uuid.UUID     `db:"id" json:"id"`
	Url           *string       `db:"url" json:"url"`
	Date          *string       `db:"date" json:"date"`
	CategorizedAt *time.Time    `db:"categorized_at" json:"categorized_at"`
	CategorizedBy uuid.NullUUID `db:"categorized_by" json:"categorized_by"`
}

func (q *Queries) UpdateImage(ctx context.Context, arg UpdateImageParams) (Image, error) {
	row := q.db.QueryRow(ctx, updateImage,
		arg.ID,
		arg.Url,
		arg.Date,
		arg.CategorizedAt,
		arg.CategorizedBy,
	)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Width,
		&i.Height,
		&i.Checksum,
		&i.Date,
		&i.Organized,
		&i.CategorizedAt,
		&i.CategorizedBy,
	)
	return i, err
}
