// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"context"

	"github.com/gofrs/uuid"
)

type Querier interface {
	CancelUserEdits(ctx context.Context, userID uuid.NullUUID) error
	ClearScenePerformerAlias(ctx context.Context, arg ClearScenePerformerAliasParams) error
	CountNotificationsByUser(ctx context.Context, arg CountNotificationsByUserParams) (int64, error)
	CountScenesByPerformer(ctx context.Context, performerID uuid.UUID) (int64, error)
	CountUserEditsByStatus(ctx context.Context, userID uuid.NullUUID) ([]CountUserEditsByStatusRow, error)
	CountUsers(ctx context.Context) (int64, error)
	CountVotesByType(ctx context.Context, userID uuid.UUID) ([]CountVotesByTypeRow, error)
	// Draft queries
	CreateDraft(ctx context.Context, arg CreateDraftParams) (Draft, error)
	// Edit queries
	CreateEdit(ctx context.Context, arg CreateEditParams) (Edit, error)
	// Edit comments
	CreateEditComment(ctx context.Context, arg CreateEditCommentParams) (EditComment, error)
	// Edit votes
	CreateEditVote(ctx context.Context, arg CreateEditVoteParams) error
	// Fingerprint queries (normalized schema)
	CreateFingerprint(ctx context.Context, arg CreateFingerprintParams) (Fingerprint, error)
	// Image queries
	CreateImage(ctx context.Context, arg CreateImageParams) (Image, error)
	// Invite key queries
	CreateInviteKey(ctx context.Context, arg CreateInviteKeyParams) (InviteKey, error)
	CreateOrReplaceFingerprint(ctx context.Context, arg CreateOrReplaceFingerprintParams) error
	// Performer queries
	CreatePerformer(ctx context.Context, arg CreatePerformerParams) (Performer, error)
	CreatePerformerAliases(ctx context.Context, arg []CreatePerformerAliasesParams) (int64, error)
	CreatePerformerEdit(ctx context.Context, arg CreatePerformerEditParams) error
	CreatePerformerFavorite(ctx context.Context, arg CreatePerformerFavoriteParams) error
	CreatePerformerImages(ctx context.Context, arg []CreatePerformerImagesParams) (int64, error)
	CreatePerformerPiercings(ctx context.Context, arg []CreatePerformerPiercingsParams) (int64, error)
	// Performer redirects
	CreatePerformerRedirect(ctx context.Context, arg CreatePerformerRedirectParams) error
	CreatePerformerTattoos(ctx context.Context, arg []CreatePerformerTattoosParams) (int64, error)
	CreatePerformerURLs(ctx context.Context, arg []CreatePerformerURLsParams) (int64, error)
	// Scene queries
	CreateScene(ctx context.Context, arg CreateSceneParams) (Scene, error)
	CreateSceneEdit(ctx context.Context, arg CreateSceneEditParams) error
	CreateSceneFingerprints(ctx context.Context, arg []CreateSceneFingerprintsParams) (int64, error)
	CreateSceneImages(ctx context.Context, arg []CreateSceneImagesParams) (int64, error)
	// Scene performers
	CreateScenePerformers(ctx context.Context, arg []CreateScenePerformersParams) (int64, error)
	// Scene redirects
	CreateSceneRedirect(ctx context.Context, arg CreateSceneRedirectParams) error
	// Scene tags management
	CreateSceneTags(ctx context.Context, arg []CreateSceneTagsParams) (int64, error)
	// Scene URLs
	CreateSceneURLs(ctx context.Context, arg []CreateSceneURLsParams) (int64, error)
	// Site queries
	CreateSite(ctx context.Context, arg CreateSiteParams) (Site, error)
	// Studio queries
	CreateStudio(ctx context.Context, arg CreateStudioParams) (Studio, error)
	// Studio aliases
	CreateStudioAliases(ctx context.Context, arg []CreateStudioAliasesParams) (int64, error)
	CreateStudioEdit(ctx context.Context, arg CreateStudioEditParams) error
	// Studio favorites
	CreateStudioFavorite(ctx context.Context, arg CreateStudioFavoriteParams) error
	// Studio images
	CreateStudioImages(ctx context.Context, arg []CreateStudioImagesParams) (int64, error)
	// Studio redirects
	CreateStudioRedirect(ctx context.Context, arg CreateStudioRedirectParams) error
	// Studio URLs
	CreateStudioURLs(ctx context.Context, arg []CreateStudioURLsParams) (int64, error)
	// Tag queries
	CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error)
	// Tag aliases
	CreateTagAliases(ctx context.Context, arg []CreateTagAliasesParams) (int64, error)
	// Tag category queries
	CreateTagCategory(ctx context.Context, arg CreateTagCategoryParams) (TagCategory, error)
	CreateTagEdit(ctx context.Context, arg CreateTagEditParams) error
	// Tag redirects
	CreateTagRedirect(ctx context.Context, arg CreateTagRedirectParams) error
	// User queries
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// User notification subscriptions
	CreateUserNotificationSubscriptions(ctx context.Context, arg []CreateUserNotificationSubscriptionsParams) (int64, error)
	// User roles
	CreateUserRoles(ctx context.Context, arg []CreateUserRolesParams) (int64, error)
	// User token queries
	CreateUserToken(ctx context.Context, arg CreateUserTokenParams) (UserToken, error)
	DeleteAllSceneFingerprintSubmissions(ctx context.Context, arg DeleteAllSceneFingerprintSubmissionsParams) (int64, error)
	DeleteDraft(ctx context.Context, id uuid.UUID) error
	DeleteEdit(ctx context.Context, id uuid.UUID) error
	DeleteExpiredDrafts(ctx context.Context, dollar_1 interface{}) error
	DeleteExpiredUserTokens(ctx context.Context) error
	DeleteImage(ctx context.Context, id uuid.UUID) error
	DeleteInviteKey(ctx context.Context, id uuid.UUID) error
	DeletePerformer(ctx context.Context, id uuid.UUID) error
	// Performer aliases
	DeletePerformerAliases(ctx context.Context, performerID uuid.UUID) error
	DeletePerformerFavorite(ctx context.Context, arg DeletePerformerFavoriteParams) error
	// Performer favorites
	DeletePerformerFavorites(ctx context.Context, performerID uuid.UUID) error
	DeletePerformerImages(ctx context.Context, performerID uuid.UUID) error
	// Performer piercings
	DeletePerformerPiercings(ctx context.Context, performerID uuid.UUID) error
	DeletePerformerScenes(ctx context.Context, performerID uuid.UUID) error
	// Performer tattoos
	DeletePerformerTattoos(ctx context.Context, performerID uuid.UUID) error
	// Performer URLs
	DeletePerformerURLs(ctx context.Context, performerID uuid.UUID) error
	DeleteScene(ctx context.Context, id uuid.UUID) error
	DeleteSceneFingerprint(ctx context.Context, arg DeleteSceneFingerprintParams) error
	DeleteSceneFingerprintsByScene(ctx context.Context, sceneID uuid.UUID) error
	// Scene images
	DeleteSceneImages(ctx context.Context, sceneID uuid.UUID) error
	DeleteScenePerformers(ctx context.Context, sceneID uuid.UUID) error
	DeleteSceneStudios(ctx context.Context, studioID uuid.NullUUID) error
	DeleteSceneTagsByScene(ctx context.Context, sceneID uuid.UUID) error
	DeleteSceneTagsByTag(ctx context.Context, tagID uuid.UUID) error
	DeleteSceneURLs(ctx context.Context, sceneID uuid.UUID) error
	DeleteSite(ctx context.Context, id uuid.UUID) error
	DeleteStudio(ctx context.Context, id uuid.UUID) error
	DeleteStudioAliases(ctx context.Context, studioID uuid.UUID) error
	DeleteStudioFavorite(ctx context.Context, arg DeleteStudioFavoriteParams) error
	DeleteStudioFavorites(ctx context.Context, studioID uuid.UUID) error
	DeleteStudioImages(ctx context.Context, studioID uuid.UUID) error
	DeleteStudioURLs(ctx context.Context, studioID uuid.UUID) error
	DeleteTag(ctx context.Context, id uuid.UUID) error
	DeleteTagAliases(ctx context.Context, tagID uuid.UUID) error
	DeleteTagAliasesByNames(ctx context.Context, arg DeleteTagAliasesByNamesParams) error
	DeleteTagCategory(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	DeleteUserNotificationSubscriptions(ctx context.Context, userID uuid.UUID) error
	DeleteUserRoles(ctx context.Context, userID uuid.UUID) error
	DeleteUserToken(ctx context.Context, id uuid.UUID) error
	DestroyExpiredInvites(ctx context.Context) error
	DestroyExpiredNotifications(ctx context.Context) error
	FindActiveInviteKeysForUser(ctx context.Context, generatedBy uuid.UUID) ([]InviteKey, error)
	// Returns pending edits that fulfill one of the criteria for being closed:
	// * The full voting period has passed
	// * The minimum voting period has passed, and the number of votes has crossed the voting threshold.
	// The latter only applies for destructive edits. Non-destructive edits get auto-applied when sufficient votes are cast.
	FindCompletedEdits(ctx context.Context, arg FindCompletedEditsParams) ([]Edit, error)
	FindDraft(ctx context.Context, id uuid.UUID) (Draft, error)
	FindDraftsByUser(ctx context.Context, userID uuid.UUID) ([]Draft, error)
	FindEdit(ctx context.Context, id uuid.UUID) (Edit, error)
	FindExistingPerformers(ctx context.Context, arg FindExistingPerformersParams) ([]Performer, error)
	FindExistingScenes(ctx context.Context, arg FindExistingScenesParams) ([]Scene, error)
	FindImage(ctx context.Context, id uuid.UUID) (Image, error)
	FindImageByChecksum(ctx context.Context, checksum string) (Image, error)
	FindImageIdsByPerformerIds(ctx context.Context, dollar_1 []uuid.UUID) ([]PerformerImage, error)
	FindImageIdsBySceneIds(ctx context.Context, dollar_1 []uuid.UUID) ([]SceneImage, error)
	FindImageIdsByStudioIds(ctx context.Context, dollar_1 []uuid.UUID) ([]StudioImage, error)
	FindImagesByIds(ctx context.Context, dollar_1 []uuid.UUID) ([]Image, error)
	FindImagesBySceneID(ctx context.Context, id uuid.UUID) ([]Image, error)
	FindImagesByStudioID(ctx context.Context, id uuid.UUID) ([]Image, error)
	FindInviteKey(ctx context.Context, id uuid.UUID) (InviteKey, error)
	// Find merge target IDs for performers (for merges where these are sources)
	FindMergeIDsByPerformerIds(ctx context.Context, performerIds []uuid.UUID) ([]FindMergeIDsByPerformerIdsRow, error)
	// Find merge source IDs for performers (for merges where these are targets)
	FindMergeIDsBySourcePerformerIds(ctx context.Context, performerIds []uuid.UUID) ([]FindMergeIDsBySourcePerformerIdsRow, error)
	// Notification queries
	FindNotificationsByUser(ctx context.Context, arg FindNotificationsByUserParams) ([]Notification, error)
	FindPendingPerformerCreation(ctx context.Context, arg FindPendingPerformerCreationParams) ([]Edit, error)
	FindPendingSceneCreation(ctx context.Context, arg FindPendingSceneCreationParams) ([]Edit, error)
	FindPerformer(ctx context.Context, id uuid.UUID) (Performer, error)
	// Get aliases for multiple performers
	FindPerformerAliasesByIds(ctx context.Context, performerIds []uuid.UUID) ([]PerformerAlias, error)
	FindPerformerByAlias(ctx context.Context, upper interface{}) (Performer, error)
	FindPerformerByName(ctx context.Context, upper interface{}) (Performer, error)
	// Check favorite status for multiple performers for a specific user
	FindPerformerFavoritesByIds(ctx context.Context, arg FindPerformerFavoritesByIdsParams) ([]FindPerformerFavoritesByIdsRow, error)
	// Get piercings for multiple performers
	FindPerformerPiercingsByIds(ctx context.Context, performerIds []uuid.UUID) ([]PerformerPiercing, error)
	// Get tattoos for multiple performers
	FindPerformerTattoosByIds(ctx context.Context, performerIds []uuid.UUID) ([]PerformerTattoo, error)
	// Get URLs for multiple performers
	FindPerformerUrlsByIds(ctx context.Context, performerIds []uuid.UUID) ([]PerformerUrl, error)
	FindPerformerWithRedirect(ctx context.Context, id uuid.UUID) ([]Performer, error)
	FindPerformersByIds(ctx context.Context, dollar_1 []uuid.UUID) ([]Performer, error)
	FindPerformersByURL(ctx context.Context, arg FindPerformersByURLParams) ([]Performer, error)
	FindScene(ctx context.Context, id uuid.UUID) (Scene, error)
	// Get performer appearances for multiple scenes
	FindSceneAppearancesByIds(ctx context.Context, sceneIds []uuid.UUID) ([]FindSceneAppearancesByIdsRow, error)
	FindSceneByURL(ctx context.Context, arg FindSceneByURLParams) ([]Scene, error)
	// Get URLs for multiple scenes
	FindSceneUrlsByIds(ctx context.Context, sceneIds []uuid.UUID) ([]SceneUrl, error)
	// Scene fingerprints (use fingerprint.sql for most fingerprint operations)
	FindScenesByFullFingerprintsWithHash(ctx context.Context, arg FindScenesByFullFingerprintsWithHashParams) ([]FindScenesByFullFingerprintsWithHashRow, error)
	FindSitesByIds(ctx context.Context, dollar_1 []uuid.UUID) ([]Site, error)
	FindStudio(ctx context.Context, id uuid.UUID) (Studio, error)
	// Get aliases for multiple studios
	FindStudioAliasesByIds(ctx context.Context, studioIds []uuid.UUID) ([]StudioAlias, error)
	FindStudioByAlias(ctx context.Context, upper interface{}) (Studio, error)
	FindStudioByName(ctx context.Context, upper interface{}) (Studio, error)
	// Check favorite status for multiple studios for a specific user
	FindStudioFavoritesByIds(ctx context.Context, arg FindStudioFavoritesByIdsParams) ([]FindStudioFavoritesByIdsRow, error)
	// Get URLs for multiple studios
	FindStudioUrlsByIds(ctx context.Context, studioIds []uuid.UUID) ([]StudioUrl, error)
	FindStudioWithRedirect(ctx context.Context, id uuid.UUID) (Studio, error)
	FindTag(ctx context.Context, id uuid.UUID) (Tag, error)
	FindTagByAlias(ctx context.Context, upper interface{}) (Tag, error)
	FindTagByName(ctx context.Context, upper interface{}) (Tag, error)
	FindTagByNameOrAlias(ctx context.Context, lower string) (Tag, error)
	FindTagCategory(ctx context.Context, id uuid.UUID) (TagCategory, error)
	// Bulk query to find tag IDs for multiple scene IDs
	FindTagIdsBySceneIds(ctx context.Context, sceneIds []uuid.UUID) ([]SceneTag, error)
	FindTagWithRedirect(ctx context.Context, id uuid.UUID) ([]Tag, error)
	FindTagsByIds(ctx context.Context, dollar_1 []uuid.UUID) ([]Tag, error)
	FindTagsBySceneID(ctx context.Context, sceneID uuid.UUID) ([]Tag, error)
	FindUnreadNotificationsByUser(ctx context.Context, arg FindUnreadNotificationsByUserParams) ([]Notification, error)
	FindUnusedImages(ctx context.Context) ([]Image, error)
	FindUser(ctx context.Context, id uuid.UUID) (User, error)
	FindUserByEmail(ctx context.Context, upper interface{}) (User, error)
	FindUserByName(ctx context.Context, name string) (User, error)
	FindUserToken(ctx context.Context, id uuid.UUID) (UserToken, error)
	FindUserTokensByEmail(ctx context.Context, dollar_1 string) ([]UserToken, error)
	FindUserTokensByInviteKey(ctx context.Context, dollar_1 uuid.UUID) ([]UserToken, error)
	// Get all fingerprints for multiple scenes with aggregated vote data
	// When onlySubmitted is true, pass the actual user ID, when false pass NULL
	GetAllFingerprints(ctx context.Context, arg GetAllFingerprintsParams) ([]GetAllFingerprintsRow, error)
	GetAllSceneFingerprints(ctx context.Context, sceneID uuid.UUID) ([]GetAllSceneFingerprintsRow, error)
	GetAllTagCategories(ctx context.Context) ([]TagCategory, error)
	GetChildStudios(ctx context.Context, parentStudioID uuid.NullUUID) ([]Studio, error)
	GetEditComments(ctx context.Context, editID uuid.UUID) ([]EditComment, error)
	GetEditCommentsByIds(ctx context.Context, dollar_1 []uuid.UUID) ([]EditComment, error)
	GetEditPerformerAliases(ctx context.Context, id uuid.UUID) ([]string, error)
	GetEditPerformerPiercings(ctx context.Context, id uuid.UUID) ([]GetEditPerformerPiercingsRow, error)
	GetEditPerformerTattoos(ctx context.Context, id uuid.UUID) ([]GetEditPerformerTattoosRow, error)
	GetEditTargetID(ctx context.Context, id uuid.UUID) (GetEditTargetIDRow, error)
	GetEditVotes(ctx context.Context, editID uuid.UUID) ([]EditVote, error)
	GetEditsByIds(ctx context.Context, dollar_1 []uuid.UUID) ([]Edit, error)
	GetEditsByPerformer(ctx context.Context, performerID uuid.UUID) ([]Edit, error)
	GetEditsByScene(ctx context.Context, sceneID uuid.UUID) ([]Edit, error)
	GetEditsByStudio(ctx context.Context, studioID uuid.UUID) ([]Edit, error)
	GetEditsByTag(ctx context.Context, tagID uuid.UUID) ([]Edit, error)
	GetFingerprint(ctx context.Context, arg GetFingerprintParams) (Fingerprint, error)
	// Gets current images for target entity and merges with edit's added_images/removed_images
	GetImagesForEdit(ctx context.Context, id uuid.UUID) ([]Image, error)
	// Gets current performers for target entity and merges with edit's added_performers/removed_performers
	GetMergedPerformersForEdit(ctx context.Context, id uuid.UUID) ([]GetMergedPerformersForEditRow, error)
	// Gets current aliases for target studio entity and merges with edit's added_aliases/removed_aliases
	GetMergedStudioAliasesForEdit(ctx context.Context, id uuid.UUID) ([]string, error)
	// Gets current aliases for target tag entity and merges with edit's added_aliases/removed_aliases
	GetMergedTagAliasesForEdit(ctx context.Context, id uuid.UUID) ([]string, error)
	// Gets current tags for target entity and merges with edit's added_tags/removed_tags
	GetMergedTagsForEdit(ctx context.Context, id uuid.UUID) ([]Tag, error)
	// URL merging queries for edits
	// result: URL
	// Gets current URLs for target entity and merges with edit's added_urls/removed_urls
	GetMergedURLsForEdit(ctx context.Context, id uuid.UUID) ([]GetMergedURLsForEditRow, error)
	GetPerformerAliases(ctx context.Context, performerID uuid.UUID) ([]string, error)
	// Performer images
	GetPerformerImages(ctx context.Context, performerID uuid.UUID) ([]Image, error)
	GetPerformerPiercings(ctx context.Context, performerID uuid.UUID) ([]GetPerformerPiercingsRow, error)
	GetPerformerTattoos(ctx context.Context, performerID uuid.UUID) ([]GetPerformerTattoosRow, error)
	GetPerformerURLs(ctx context.Context, performerID uuid.UUID) ([]GetPerformerURLsRow, error)
	GetScenePerformers(ctx context.Context, sceneID uuid.UUID) ([]GetScenePerformersRow, error)
	GetSceneTags(ctx context.Context, sceneID uuid.UUID) ([]Tag, error)
	GetSceneURLs(ctx context.Context, sceneID uuid.UUID) ([]GetSceneURLsRow, error)
	GetScenes(ctx context.Context, dollar_1 []uuid.UUID) ([]Scene, error)
	GetSite(ctx context.Context, id uuid.UUID) (Site, error)
	GetStudioAliases(ctx context.Context, studioID uuid.UUID) ([]string, error)
	GetStudioImages(ctx context.Context, studioID uuid.UUID) ([]uuid.UUID, error)
	GetStudioURLs(ctx context.Context, studioID uuid.UUID) ([]StudioUrl, error)
	GetStudios(ctx context.Context, dollar_1 []uuid.UUID) ([]Studio, error)
	GetStudiosByPerformer(ctx context.Context, performerID uuid.UUID) ([]GetStudiosByPerformerRow, error)
	// Get studios where performer has scenes, filtered to a studio network (the studio, its parent, and children)
	GetStudiosByPerformerAndNetwork(ctx context.Context, arg GetStudiosByPerformerAndNetworkParams) ([]GetStudiosByPerformerAndNetworkRow, error)
	GetTagAliases(ctx context.Context, tagID uuid.UUID) ([]string, error)
	GetTagCategoriesByIds(ctx context.Context, dollar_1 []uuid.UUID) ([]TagCategory, error)
	GetUserNotificationSubscriptions(ctx context.Context, userID uuid.UUID) ([]NotificationType, error)
	GetUserRoles(ctx context.Context, userID uuid.UUID) ([]string, error)
	InviteKeyUsed(ctx context.Context, id uuid.UUID) (*int, error)
	IsImageUnused(ctx context.Context, id uuid.UUID) (bool, error)
	MarkAllNotificationsRead(ctx context.Context, userID uuid.UUID) error
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error
	MoveSceneFingerprintSubmissions(ctx context.Context, arg MoveSceneFingerprintSubmissionsParams) (int64, error)
	ReassignPerformerAliases(ctx context.Context, arg ReassignPerformerAliasesParams) error
	ReassignPerformerFavorites(ctx context.Context, arg ReassignPerformerFavoritesParams) error
	ReassignStudioFavorites(ctx context.Context, arg ReassignStudioFavoritesParams) error
	ResetVotes(ctx context.Context, editID uuid.UUID) error
	SearchPerformers(ctx context.Context, arg SearchPerformersParams) ([]Performer, error)
	SearchScenes(ctx context.Context, arg SearchScenesParams) ([]Scene, error)
	SearchStudios(ctx context.Context, arg SearchStudiosParams) ([]Studio, error)
	SearchTags(ctx context.Context, arg SearchTagsParams) ([]Tag, error)
	SetScenePerformerAlias(ctx context.Context, arg SetScenePerformerAliasParams) error
	SoftDeletePerformer(ctx context.Context, id uuid.UUID) (Performer, error)
	SoftDeleteScene(ctx context.Context, id uuid.UUID) (Scene, error)
	SoftDeleteStudio(ctx context.Context, id uuid.UUID) (Studio, error)
	SoftDeleteTag(ctx context.Context, id uuid.UUID) (Tag, error)
	SubmittedHashExists(ctx context.Context, arg SubmittedHashExistsParams) (bool, error)
	TriggerDownvoteEditNotifications(ctx context.Context, id uuid.UUID) error
	TriggerEditCommentNotifications(ctx context.Context, id uuid.UUID) error
	TriggerFailedEditNotifications(ctx context.Context, id uuid.UUID) error
	TriggerPerformerEditNotifications(ctx context.Context, id uuid.UUID) error
	TriggerSceneCreationNotifications(ctx context.Context, id uuid.UUID) error
	TriggerSceneEditNotifications(ctx context.Context, id uuid.UUID) error
	TriggerStudioEditNotifications(ctx context.Context, id uuid.UUID) error
	TriggerUpdatedEditNotifications(ctx context.Context, id uuid.UUID) error
	UpdateEdit(ctx context.Context, arg UpdateEditParams) (Edit, error)
	UpdatePerformer(ctx context.Context, arg UpdatePerformerParams) (Performer, error)
	UpdatePerformerRedirects(ctx context.Context, arg UpdatePerformerRedirectsParams) error
	UpdateScene(ctx context.Context, arg UpdateSceneParams) (Scene, error)
	UpdateSceneRedirects(ctx context.Context, arg UpdateSceneRedirectsParams) error
	UpdateSceneStudios(ctx context.Context, arg UpdateSceneStudiosParams) error
	UpdateSceneTagsForMerge(ctx context.Context, arg UpdateSceneTagsForMergeParams) error
	UpdateSite(ctx context.Context, arg UpdateSiteParams) (Site, error)
	UpdateStudio(ctx context.Context, arg UpdateStudioParams) (Studio, error)
	UpdateStudioRedirects(ctx context.Context, arg UpdateStudioRedirectsParams) error
	UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error)
	UpdateTagCategory(ctx context.Context, arg UpdateTagCategoryParams) (TagCategory, error)
	UpdateTagRedirects(ctx context.Context, arg UpdateTagRedirectsParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserAPIKey(ctx context.Context, arg UpdateUserAPIKeyParams) error
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error
	UpdateUserInviteTokenCount(ctx context.Context, arg UpdateUserInviteTokenCountParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
