// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: site_category.sql

package queries

import (
	"context"
)

const createSiteCategory = `-- name: CreateSiteCategory :one

INSERT INTO site_categories (name, description, sort_order, created_at, updated_at)
VALUES ($1, $2, $3, now(), now())
RETURNING id, name, description, sort_order, created_at, updated_at
`

type CreateSiteCategoryParams struct {
	Name        string  `db:"name" json:"name"`
	Description *string `db:"description" json:"description"`
	SortOrder   int     `db:"sort_order" json:"sort_order"`
}

// Site category queries
func (q *Queries) CreateSiteCategory(ctx context.Context, arg CreateSiteCategoryParams) (SiteCategory, error) {
	row := q.db.QueryRow(ctx, createSiteCategory, arg.Name, arg.Description, arg.SortOrder)
	var i SiteCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSiteCategory = `-- name: DeleteSiteCategory :exec
DELETE FROM site_categories WHERE id = $1
`

func (q *Queries) DeleteSiteCategory(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, deleteSiteCategory, id)
	return err
}

const findSiteCategory = `-- name: FindSiteCategory :one
SELECT id, name, description, sort_order, created_at, updated_at FROM site_categories WHERE id = $1
`

func (q *Queries) FindSiteCategory(ctx context.Context, id int) (SiteCategory, error) {
	row := q.db.QueryRow(ctx, findSiteCategory, id)
	var i SiteCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllSiteCategories = `-- name: GetAllSiteCategories :many
SELECT id, name, description, sort_order, created_at, updated_at FROM site_categories ORDER BY sort_order ASC, name ASC
`

func (q *Queries) GetAllSiteCategories(ctx context.Context) ([]SiteCategory, error) {
	rows, err := q.db.Query(ctx, getAllSiteCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SiteCategory{}
	for rows.Next() {
		var i SiteCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSiteCategoriesByIds = `-- name: GetSiteCategoriesByIds :many
SELECT id, name, description, sort_order, created_at, updated_at FROM site_categories WHERE id = ANY($1::int[])
`

func (q *Queries) GetSiteCategoriesByIds(ctx context.Context, dollar_1 []int) ([]SiteCategory, error) {
	rows, err := q.db.Query(ctx, getSiteCategoriesByIds, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SiteCategory{}
	for rows.Next() {
		var i SiteCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSiteCategory = `-- name: UpdateSiteCategory :one
UPDATE site_categories
SET name = $2, description = $3, sort_order = $4, updated_at = now()
WHERE id = $1
RETURNING id, name, description, sort_order, created_at, updated_at
`

type UpdateSiteCategoryParams struct {
	ID          int     `db:"id" json:"id"`
	Name        string  `db:"name" json:"name"`
	Description *string `db:"description" json:"description"`
	SortOrder   int     `db:"sort_order" json:"sort_order"`
}

func (q *Queries) UpdateSiteCategory(ctx context.Context, arg UpdateSiteCategoryParams) (SiteCategory, error) {
	row := q.db.QueryRow(ctx, updateSiteCategory,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.SortOrder,
	)
	var i SiteCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
