// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: draft.sql

package db

import (
	"context"

	"github.com/gofrs/uuid"
)

const createDraft = `-- name: CreateDraft :one

INSERT INTO drafts (id, user_id, type, data, created_at)
VALUES ($1, $2, $3, $4, now())
RETURNING id, user_id, type, data, created_at
`

type CreateDraftParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	Type   string    `db:"type" json:"type"`
	Data   []byte    `db:"data" json:"data"`
}

// Draft queries
func (q *Queries) CreateDraft(ctx context.Context, arg CreateDraftParams) (Draft, error) {
	row := q.db.QueryRow(ctx, createDraft,
		arg.ID,
		arg.UserID,
		arg.Type,
		arg.Data,
	)
	var i Draft
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDraft = `-- name: DeleteDraft :exec
DELETE FROM drafts WHERE id = $1
`

func (q *Queries) DeleteDraft(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDraft, id)
	return err
}

const deleteExpiredDrafts = `-- name: DeleteExpiredDrafts :exec
DELETE FROM drafts WHERE created_at <= (now()::timestamp - (INTERVAL '1 second' * $1))
`

func (q *Queries) DeleteExpiredDrafts(ctx context.Context, dollar_1 interface{}) error {
	_, err := q.db.Exec(ctx, deleteExpiredDrafts, dollar_1)
	return err
}

const findDraft = `-- name: FindDraft :one
SELECT id, user_id, type, data, created_at FROM drafts WHERE id = $1
`

func (q *Queries) FindDraft(ctx context.Context, id uuid.UUID) (Draft, error) {
	row := q.db.QueryRow(ctx, findDraft, id)
	var i Draft
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const findDraftsByUser = `-- name: FindDraftsByUser :many
SELECT id, user_id, type, data, created_at FROM drafts WHERE user_id = $1
`

func (q *Queries) FindDraftsByUser(ctx context.Context, userID uuid.UUID) ([]Draft, error) {
	rows, err := q.db.Query(ctx, findDraftsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Draft{}
	for rows.Next() {
		var i Draft
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findExpiredDrafts = `-- name: FindExpiredDrafts :many
SELECT id, user_id, type, data, created_at FROM drafts WHERE created_at <= (now()::timestamp - (INTERVAL '1 second' * $1))
`

func (q *Queries) FindExpiredDrafts(ctx context.Context, dollar_1 interface{}) ([]Draft, error) {
	rows, err := q.db.Query(ctx, findExpiredDrafts, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Draft{}
	for rows.Next() {
		var i Draft
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
