// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: invite_key.sql

package db

import (
	"context"
	"time"

	"github.com/gofrs/uuid"
)

const createInviteKey = `-- name: CreateInviteKey :one

INSERT INTO invite_keys (id, generated_by, uses, expire_time, generated_at)
VALUES ($1, $2, $3, $4, now())
RETURNING id, generated_by, generated_at, uses, expire_time
`

type CreateInviteKeyParams struct {
	ID          uuid.UUID  `db:"id" json:"id"`
	GeneratedBy uuid.UUID  `db:"generated_by" json:"generated_by"`
	Uses        *int       `db:"uses" json:"uses"`
	ExpireTime  *time.Time `db:"expire_time" json:"expire_time"`
}

// Invite key queries
func (q *Queries) CreateInviteKey(ctx context.Context, arg CreateInviteKeyParams) (InviteKey, error) {
	row := q.db.QueryRow(ctx, createInviteKey,
		arg.ID,
		arg.GeneratedBy,
		arg.Uses,
		arg.ExpireTime,
	)
	var i InviteKey
	err := row.Scan(
		&i.ID,
		&i.GeneratedBy,
		&i.GeneratedAt,
		&i.Uses,
		&i.ExpireTime,
	)
	return i, err
}

const deleteInviteKey = `-- name: DeleteInviteKey :exec
DELETE FROM invite_keys WHERE id = $1
`

func (q *Queries) DeleteInviteKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteInviteKey, id)
	return err
}

const destroyExpiredInvites = `-- name: DestroyExpiredInvites :exec
DELETE FROM invite_keys WHERE expire_time IS NOT NULL AND expire_time < NOW()
`

func (q *Queries) DestroyExpiredInvites(ctx context.Context) error {
	_, err := q.db.Exec(ctx, destroyExpiredInvites)
	return err
}

const findActiveInviteKeysForUser = `-- name: FindActiveInviteKeysForUser :many
SELECT i.id, i.generated_by, i.generated_at, i.uses, i.expire_time FROM invite_keys i
LEFT JOIN (
  SELECT uuid(data->>'invite_key') as invite_key, COUNT(*) as count
  FROM user_tokens
  WHERE expires_at > NOW()
  GROUP BY data->>'invite_key'
) AS used ON used.invite_key = i.id
WHERE i.generated_by = $1
AND (i.expire_time IS NULL OR i.expire_time > NOW())
AND (used.invite_key IS NULL OR i.uses IS NULL OR used.count < i.uses)
`

func (q *Queries) FindActiveInviteKeysForUser(ctx context.Context, generatedBy uuid.UUID) ([]InviteKey, error) {
	rows, err := q.db.Query(ctx, findActiveInviteKeysForUser, generatedBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InviteKey{}
	for rows.Next() {
		var i InviteKey
		if err := rows.Scan(
			&i.ID,
			&i.GeneratedBy,
			&i.GeneratedAt,
			&i.Uses,
			&i.ExpireTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findActiveKeysForUser = `-- name: FindActiveKeysForUser :many
SELECT i.id, i.generated_by, i.generated_at, i.uses, i.expire_time FROM invite_keys i 
LEFT JOIN (
  SELECT uuid(data->>'invite_key') as invite_key, COUNT(*) as count
  FROM user_tokens
  WHERE type = 'NEW_USER' 
  GROUP BY data->>'invite_key'
) AS used ON used.invite_key = i.id
WHERE i.generated_by = $1 
AND (i.expire_time IS NULL OR i.expire_time > $2)
AND (i.uses IS NULL OR i.uses > coalesce(used.count, 0))
`

type FindActiveKeysForUserParams struct {
	GeneratedBy uuid.UUID  `db:"generated_by" json:"generated_by"`
	ExpireTime  *time.Time `db:"expire_time" json:"expire_time"`
}

func (q *Queries) FindActiveKeysForUser(ctx context.Context, arg FindActiveKeysForUserParams) ([]InviteKey, error) {
	rows, err := q.db.Query(ctx, findActiveKeysForUser, arg.GeneratedBy, arg.ExpireTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InviteKey{}
	for rows.Next() {
		var i InviteKey
		if err := rows.Scan(
			&i.ID,
			&i.GeneratedBy,
			&i.GeneratedAt,
			&i.Uses,
			&i.ExpireTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findInviteKey = `-- name: FindInviteKey :one
SELECT id, generated_by, generated_at, uses, expire_time FROM invite_keys WHERE id = $1
`

func (q *Queries) FindInviteKey(ctx context.Context, id uuid.UUID) (InviteKey, error) {
	row := q.db.QueryRow(ctx, findInviteKey, id)
	var i InviteKey
	err := row.Scan(
		&i.ID,
		&i.GeneratedBy,
		&i.GeneratedAt,
		&i.Uses,
		&i.ExpireTime,
	)
	return i, err
}

const inviteKeyUsed = `-- name: InviteKeyUsed :one
UPDATE invite_keys
SET uses = GREATEST(0, uses - 1)
WHERE id = $1 AND uses IS NOT NULL AND uses > 0
RETURNING uses
`

func (q *Queries) InviteKeyUsed(ctx context.Context, id uuid.UUID) (*int, error) {
	row := q.db.QueryRow(ctx, inviteKeyUsed, id)
	var uses *int
	err := row.Scan(&uses)
	return uses, err
}
