// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/gofrs/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type NotificationType string

const (
	NotificationTypeFAVORITEPERFORMERSCENE NotificationType = "FAVORITE_PERFORMER_SCENE"
	NotificationTypeFAVORITEPERFORMEREDIT  NotificationType = "FAVORITE_PERFORMER_EDIT"
	NotificationTypeFAVORITESTUDIOSCENE    NotificationType = "FAVORITE_STUDIO_SCENE"
	NotificationTypeFAVORITESTUDIOEDIT     NotificationType = "FAVORITE_STUDIO_EDIT"
	NotificationTypeCOMMENTOWNEDIT         NotificationType = "COMMENT_OWN_EDIT"
	NotificationTypeDOWNVOTEOWNEDIT        NotificationType = "DOWNVOTE_OWN_EDIT"
	NotificationTypeFAILEDOWNEDIT          NotificationType = "FAILED_OWN_EDIT"
	NotificationTypeCOMMENTCOMMENTEDEDIT   NotificationType = "COMMENT_COMMENTED_EDIT"
	NotificationTypeCOMMENTVOTEDEDIT       NotificationType = "COMMENT_VOTED_EDIT"
	NotificationTypeUPDATEDEDIT            NotificationType = "UPDATED_EDIT"
	NotificationTypeFINGERPRINTEDSCENEEDIT NotificationType = "FINGERPRINTED_SCENE_EDIT"
)

func (e *NotificationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationType(s)
	case string:
		*e = NotificationType(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationType: %T", src)
	}
	return nil
}

type NullNotificationType struct {
	NotificationType NotificationType `json:"notification_type"`
	Valid            bool             `json:"valid"` // Valid is true if NotificationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationType) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationType), nil
}

type Draft struct {
	ID        uuid.UUID        `db:"id" json:"id"`
	UserID    uuid.UUID        `db:"user_id" json:"user_id"`
	Type      string           `db:"type" json:"type"`
	Data      []byte           `db:"data" json:"data"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type Edit struct {
	ID          uuid.UUID        `db:"id" json:"id"`
	UserID      uuid.NullUUID    `db:"user_id" json:"user_id"`
	Operation   string           `db:"operation" json:"operation"`
	TargetType  string           `db:"target_type" json:"target_type"`
	Data        []byte           `db:"data" json:"data"`
	Votes       int32            `db:"votes" json:"votes"`
	Status      string           `db:"status" json:"status"`
	Applied     bool             `db:"applied" json:"applied"`
	CreatedAt   pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	ClosedAt    pgtype.Timestamp `db:"closed_at" json:"closed_at"`
	Bot         bool             `db:"bot" json:"bot"`
	UpdateCount int32            `db:"update_count" json:"update_count"`
}

type EditComment struct {
	ID        uuid.UUID        `db:"id" json:"id"`
	EditID    uuid.UUID        `db:"edit_id" json:"edit_id"`
	UserID    uuid.NullUUID    `db:"user_id" json:"user_id"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
	Text      string           `db:"text" json:"text"`
}

type EditVote struct {
	EditID    uuid.UUID        `db:"edit_id" json:"edit_id"`
	UserID    uuid.UUID        `db:"user_id" json:"user_id"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
	Vote      string           `db:"vote" json:"vote"`
}

type Fingerprint struct {
	ID        int32  `db:"id" json:"id"`
	Hash      string `db:"hash" json:"hash"`
	Algorithm string `db:"algorithm" json:"algorithm"`
}

type Image struct {
	ID       uuid.UUID   `db:"id" json:"id"`
	Url      pgtype.Text `db:"url" json:"url"`
	Width    int32       `db:"width" json:"width"`
	Height   int32       `db:"height" json:"height"`
	Checksum string      `db:"checksum" json:"checksum"`
}

type InviteKey struct {
	ID          uuid.UUID        `db:"id" json:"id"`
	GeneratedBy uuid.UUID        `db:"generated_by" json:"generated_by"`
	GeneratedAt pgtype.Timestamp `db:"generated_at" json:"generated_at"`
	Uses        pgtype.Int4      `db:"uses" json:"uses"`
	ExpireTime  pgtype.Timestamp `db:"expire_time" json:"expire_time"`
}

type Notification struct {
	UserID    uuid.UUID        `db:"user_id" json:"user_id"`
	Type      NotificationType `db:"type" json:"type"`
	ID        uuid.UUID        `db:"id" json:"id"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
	ReadAt    pgtype.Timestamp `db:"read_at" json:"read_at"`
}

type Performer struct {
	ID              uuid.UUID        `db:"id" json:"id"`
	Name            string           `db:"name" json:"name"`
	Disambiguation  pgtype.Text      `db:"disambiguation" json:"disambiguation"`
	Gender          pgtype.Text      `db:"gender" json:"gender"`
	Ethnicity       pgtype.Text      `db:"ethnicity" json:"ethnicity"`
	Country         pgtype.Text      `db:"country" json:"country"`
	EyeColor        pgtype.Text      `db:"eye_color" json:"eye_color"`
	HairColor       pgtype.Text      `db:"hair_color" json:"hair_color"`
	Height          pgtype.Int4      `db:"height" json:"height"`
	CupSize         pgtype.Text      `db:"cup_size" json:"cup_size"`
	BandSize        pgtype.Int4      `db:"band_size" json:"band_size"`
	HipSize         pgtype.Int4      `db:"hip_size" json:"hip_size"`
	WaistSize       pgtype.Int4      `db:"waist_size" json:"waist_size"`
	BreastType      pgtype.Text      `db:"breast_type" json:"breast_type"`
	CareerStartYear pgtype.Int4      `db:"career_start_year" json:"career_start_year"`
	CareerEndYear   pgtype.Int4      `db:"career_end_year" json:"career_end_year"`
	CreatedAt       pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	Deleted         bool             `db:"deleted" json:"deleted"`
	Birthdate       pgtype.Text      `db:"birthdate" json:"birthdate"`
	Deathdate       pgtype.Text      `db:"deathdate" json:"deathdate"`
}

type PerformerAlias struct {
	PerformerID uuid.UUID `db:"performer_id" json:"performer_id"`
	Alias       string    `db:"alias" json:"alias"`
}

type PerformerEdit struct {
	EditID      uuid.UUID `db:"edit_id" json:"edit_id"`
	PerformerID uuid.UUID `db:"performer_id" json:"performer_id"`
}

type PerformerFavorite struct {
	PerformerID uuid.UUID        `db:"performer_id" json:"performer_id"`
	UserID      uuid.UUID        `db:"user_id" json:"user_id"`
	CreatedAt   pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type PerformerImage struct {
	PerformerID uuid.UUID `db:"performer_id" json:"performer_id"`
	ImageID     uuid.UUID `db:"image_id" json:"image_id"`
}

type PerformerPiercing struct {
	PerformerID uuid.UUID   `db:"performer_id" json:"performer_id"`
	Location    pgtype.Text `db:"location" json:"location"`
	Description pgtype.Text `db:"description" json:"description"`
}

type PerformerRedirect struct {
	SourceID uuid.UUID `db:"source_id" json:"source_id"`
	TargetID uuid.UUID `db:"target_id" json:"target_id"`
}

type PerformerTattoo struct {
	PerformerID uuid.UUID   `db:"performer_id" json:"performer_id"`
	Location    pgtype.Text `db:"location" json:"location"`
	Description pgtype.Text `db:"description" json:"description"`
}

type PerformerUrl struct {
	PerformerID uuid.UUID `db:"performer_id" json:"performer_id"`
	Url         string    `db:"url" json:"url"`
	SiteID      uuid.UUID `db:"site_id" json:"site_id"`
}

type Scene struct {
	ID             uuid.UUID        `db:"id" json:"id"`
	Title          pgtype.Text      `db:"title" json:"title"`
	Details        pgtype.Text      `db:"details" json:"details"`
	StudioID       uuid.NullUUID    `db:"studio_id" json:"studio_id"`
	CreatedAt      pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	Duration       pgtype.Int4      `db:"duration" json:"duration"`
	Director       pgtype.Text      `db:"director" json:"director"`
	Deleted        bool             `db:"deleted" json:"deleted"`
	Code           pgtype.Text      `db:"code" json:"code"`
	Date           pgtype.Text      `db:"date" json:"date"`
	ProductionDate pgtype.Text      `db:"production_date" json:"production_date"`
}

type SceneEdit struct {
	EditID  uuid.UUID `db:"edit_id" json:"edit_id"`
	SceneID uuid.UUID `db:"scene_id" json:"scene_id"`
}

type SceneFingerprint struct {
	FingerprintID int32            `db:"fingerprint_id" json:"fingerprint_id"`
	SceneID       uuid.UUID        `db:"scene_id" json:"scene_id"`
	UserID        uuid.UUID        `db:"user_id" json:"user_id"`
	Duration      int32            `db:"duration" json:"duration"`
	CreatedAt     pgtype.Timestamp `db:"created_at" json:"created_at"`
	Vote          int16            `db:"vote" json:"vote"`
}

type SceneImage struct {
	SceneID uuid.UUID `db:"scene_id" json:"scene_id"`
	ImageID uuid.UUID `db:"image_id" json:"image_id"`
}

type ScenePerformer struct {
	SceneID     uuid.UUID   `db:"scene_id" json:"scene_id"`
	As          pgtype.Text `db:"as" json:"as"`
	PerformerID uuid.UUID   `db:"performer_id" json:"performer_id"`
}

type SceneRedirect struct {
	SourceID uuid.UUID `db:"source_id" json:"source_id"`
	TargetID uuid.UUID `db:"target_id" json:"target_id"`
}

type SceneSearch struct {
	SceneID        uuid.UUID   `db:"scene_id" json:"scene_id"`
	SceneTitle     string      `db:"scene_title" json:"scene_title"`
	SceneDate      string      `db:"scene_date" json:"scene_date"`
	StudioName     interface{} `db:"studio_name" json:"studio_name"`
	PerformerNames interface{} `db:"performer_names" json:"performer_names"`
	SceneCode      pgtype.Text `db:"scene_code" json:"scene_code"`
}

type SceneTag struct {
	SceneID uuid.UUID `db:"scene_id" json:"scene_id"`
	TagID   uuid.UUID `db:"tag_id" json:"tag_id"`
}

type SceneUrl struct {
	SceneID uuid.UUID `db:"scene_id" json:"scene_id"`
	Url     string    `db:"url" json:"url"`
	SiteID  uuid.UUID `db:"site_id" json:"site_id"`
}

type Site struct {
	ID          uuid.UUID        `db:"id" json:"id"`
	Name        string           `db:"name" json:"name"`
	Description pgtype.Text      `db:"description" json:"description"`
	Url         pgtype.Text      `db:"url" json:"url"`
	Regex       pgtype.Text      `db:"regex" json:"regex"`
	ValidTypes  []string         `db:"valid_types" json:"valid_types"`
	CreatedAt   pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type Studio struct {
	ID             uuid.UUID        `db:"id" json:"id"`
	Name           string           `db:"name" json:"name"`
	ParentStudioID uuid.NullUUID    `db:"parent_studio_id" json:"parent_studio_id"`
	CreatedAt      pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	Deleted        bool             `db:"deleted" json:"deleted"`
}

type StudioAlias struct {
	StudioID uuid.UUID `db:"studio_id" json:"studio_id"`
	Alias    string    `db:"alias" json:"alias"`
}

type StudioEdit struct {
	EditID   uuid.UUID `db:"edit_id" json:"edit_id"`
	StudioID uuid.UUID `db:"studio_id" json:"studio_id"`
}

type StudioFavorite struct {
	StudioID  uuid.UUID        `db:"studio_id" json:"studio_id"`
	UserID    uuid.UUID        `db:"user_id" json:"user_id"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type StudioImage struct {
	StudioID uuid.UUID `db:"studio_id" json:"studio_id"`
	ImageID  uuid.UUID `db:"image_id" json:"image_id"`
}

type StudioRedirect struct {
	SourceID uuid.UUID `db:"source_id" json:"source_id"`
	TargetID uuid.UUID `db:"target_id" json:"target_id"`
}

type StudioUrl struct {
	StudioID uuid.UUID `db:"studio_id" json:"studio_id"`
	Url      string    `db:"url" json:"url"`
	SiteID   uuid.UUID `db:"site_id" json:"site_id"`
}

type Tag struct {
	ID          uuid.UUID        `db:"id" json:"id"`
	Name        string           `db:"name" json:"name"`
	Description pgtype.Text      `db:"description" json:"description"`
	CreatedAt   pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	Deleted     bool             `db:"deleted" json:"deleted"`
	CategoryID  uuid.NullUUID    `db:"category_id" json:"category_id"`
}

type TagAlias struct {
	TagID uuid.UUID `db:"tag_id" json:"tag_id"`
	Alias string    `db:"alias" json:"alias"`
}

type TagCategory struct {
	ID          uuid.UUID        `db:"id" json:"id"`
	Group       string           `db:"group" json:"group"`
	Name        string           `db:"name" json:"name"`
	Description pgtype.Text      `db:"description" json:"description"`
	CreatedAt   pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type TagEdit struct {
	EditID uuid.UUID `db:"edit_id" json:"edit_id"`
	TagID  uuid.UUID `db:"tag_id" json:"tag_id"`
}

type TagRedirect struct {
	SourceID uuid.UUID `db:"source_id" json:"source_id"`
	TargetID uuid.UUID `db:"target_id" json:"target_id"`
}

type User struct {
	ID           uuid.UUID        `db:"id" json:"id"`
	Name         string           `db:"name" json:"name"`
	PasswordHash string           `db:"password_hash" json:"password_hash"`
	Email        string           `db:"email" json:"email"`
	ApiKey       string           `db:"api_key" json:"api_key"`
	ApiCalls     pgtype.Int4      `db:"api_calls" json:"api_calls"`
	LastApiCall  pgtype.Timestamp `db:"last_api_call" json:"last_api_call"`
	CreatedAt    pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	InvitedBy    uuid.NullUUID    `db:"invited_by" json:"invited_by"`
	InviteTokens int32            `db:"invite_tokens" json:"invite_tokens"`
}

type UserNotification struct {
	UserID uuid.UUID        `db:"user_id" json:"user_id"`
	Type   NotificationType `db:"type" json:"type"`
}

type UserRole struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	Role   string    `db:"role" json:"role"`
}

type UserToken struct {
	ID        uuid.UUID        `db:"id" json:"id"`
	Data      []byte           `db:"data" json:"data"`
	Type      string           `db:"type" json:"type"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
	ExpiresAt pgtype.Timestamp `db:"expires_at" json:"expires_at"`
}
