// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: site.sql

package db

import (
	"context"

	"github.com/gofrs/uuid"
)

const createSite = `-- name: CreateSite :one

INSERT INTO sites (id, name, description, url, regex, valid_types, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, now(), now())
RETURNING id, name, description, url, regex, valid_types, created_at, updated_at
`

type CreateSiteParams struct {
	ID          uuid.UUID `db:"id" json:"id"`
	Name        string    `db:"name" json:"name"`
	Description *string   `db:"description" json:"description"`
	Url         *string   `db:"url" json:"url"`
	Regex       *string   `db:"regex" json:"regex"`
	ValidTypes  []string  `db:"valid_types" json:"valid_types"`
}

// Site queries
func (q *Queries) CreateSite(ctx context.Context, arg CreateSiteParams) (Site, error) {
	row := q.db.QueryRow(ctx, createSite,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Url,
		arg.Regex,
		arg.ValidTypes,
	)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Url,
		&i.Regex,
		&i.ValidTypes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSite = `-- name: DeleteSite :exec
DELETE FROM sites WHERE id = $1
`

func (q *Queries) DeleteSite(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSite, id)
	return err
}

const findSitesByIds = `-- name: FindSitesByIds :many
SELECT id, name, description, url, regex, valid_types, created_at, updated_at FROM sites WHERE id = ANY($1::UUID[])
`

func (q *Queries) FindSitesByIds(ctx context.Context, dollar_1 []uuid.UUID) ([]Site, error) {
	rows, err := q.db.Query(ctx, findSitesByIds, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Site{}
	for rows.Next() {
		var i Site
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Url,
			&i.Regex,
			&i.ValidTypes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSite = `-- name: GetSite :one
SELECT id, name, description, url, regex, valid_types, created_at, updated_at FROM sites WHERE id = $1
`

func (q *Queries) GetSite(ctx context.Context, id uuid.UUID) (Site, error) {
	row := q.db.QueryRow(ctx, getSite, id)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Url,
		&i.Regex,
		&i.ValidTypes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSite = `-- name: UpdateSite :one
UPDATE sites 
SET name = $2, description = $3, url = $4, regex = $5, valid_types = $6, updated_at = now()
WHERE id = $1
RETURNING id, name, description, url, regex, valid_types, created_at, updated_at
`

type UpdateSiteParams struct {
	ID          uuid.UUID `db:"id" json:"id"`
	Name        string    `db:"name" json:"name"`
	Description *string   `db:"description" json:"description"`
	Url         *string   `db:"url" json:"url"`
	Regex       *string   `db:"regex" json:"regex"`
	ValidTypes  []string  `db:"valid_types" json:"valid_types"`
}

func (q *Queries) UpdateSite(ctx context.Context, arg UpdateSiteParams) (Site, error) {
	row := q.db.QueryRow(ctx, updateSite,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Url,
		arg.Regex,
		arg.ValidTypes,
	)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Url,
		&i.Regex,
		&i.ValidTypes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
