// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tag_category.sql

package db

import (
	"context"

	"github.com/gofrs/uuid"
)

const createTagCategory = `-- name: CreateTagCategory :one

INSERT INTO tag_categories (id, "group", name, description, created_at, updated_at)
VALUES ($1, $2, $3, $4, now(), now())
RETURNING id, "group", name, description, created_at, updated_at
`

type CreateTagCategoryParams struct {
	ID          uuid.UUID `db:"id" json:"id"`
	Group       string    `db:"group" json:"group"`
	Name        string    `db:"name" json:"name"`
	Description *string   `db:"description" json:"description"`
}

// Tag category queries
func (q *Queries) CreateTagCategory(ctx context.Context, arg CreateTagCategoryParams) (TagCategory, error) {
	row := q.db.QueryRow(ctx, createTagCategory,
		arg.ID,
		arg.Group,
		arg.Name,
		arg.Description,
	)
	var i TagCategory
	err := row.Scan(
		&i.ID,
		&i.Group,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTagCategory = `-- name: DeleteTagCategory :exec
DELETE FROM tag_categories WHERE id = $1
`

func (q *Queries) DeleteTagCategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTagCategory, id)
	return err
}

const findTagCategory = `-- name: FindTagCategory :one
SELECT id, "group", name, description, created_at, updated_at FROM tag_categories WHERE id = $1
`

func (q *Queries) FindTagCategory(ctx context.Context, id uuid.UUID) (TagCategory, error) {
	row := q.db.QueryRow(ctx, findTagCategory, id)
	var i TagCategory
	err := row.Scan(
		&i.ID,
		&i.Group,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllTagCategories = `-- name: GetAllTagCategories :many
SELECT id, "group", name, description, created_at, updated_at FROM tag_categories ORDER BY name ASC
`

func (q *Queries) GetAllTagCategories(ctx context.Context) ([]TagCategory, error) {
	rows, err := q.db.Query(ctx, getAllTagCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TagCategory{}
	for rows.Next() {
		var i TagCategory
		if err := rows.Scan(
			&i.ID,
			&i.Group,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagCategoriesByIds = `-- name: GetTagCategoriesByIds :many
SELECT id, "group", name, description, created_at, updated_at FROM tag_categories WHERE id = ANY($1::UUID[])
`

func (q *Queries) GetTagCategoriesByIds(ctx context.Context, dollar_1 []uuid.UUID) ([]TagCategory, error) {
	rows, err := q.db.Query(ctx, getTagCategoriesByIds, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TagCategory{}
	for rows.Next() {
		var i TagCategory
		if err := rows.Scan(
			&i.ID,
			&i.Group,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTagCategory = `-- name: UpdateTagCategory :one
UPDATE tag_categories 
SET "group" = $2, name = $3, description = $4, updated_at = now()
WHERE id = $1
RETURNING id, "group", name, description, created_at, updated_at
`

type UpdateTagCategoryParams struct {
	ID          uuid.UUID `db:"id" json:"id"`
	Group       string    `db:"group" json:"group"`
	Name        string    `db:"name" json:"name"`
	Description *string   `db:"description" json:"description"`
}

func (q *Queries) UpdateTagCategory(ctx context.Context, arg UpdateTagCategoryParams) (TagCategory, error) {
	row := q.db.QueryRow(ctx, updateTagCategory,
		arg.ID,
		arg.Group,
		arg.Name,
		arg.Description,
	)
	var i TagCategory
	err := row.Scan(
		&i.ID,
		&i.Group,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
