name: Frontend CI
on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        task:
          - name: Validate
            command: make ui-validate
          - name: Test
            command: make ui-test
    name: ${{ matrix.task.name }}

    steps:
      - uses: actions/checkout@v7

      - name: Install PNPM
        uses: pnpm/action-setup@v6
        with:
          version: 11

      - name: Install Node
        uses: actions/setup-node@v7
        with:
          node-version: '24'
          cache: pnpm
          cache-dependency-path: frontend/pnpm-lock.yaml

      - name: Install node packages
        run: make pre-ui

      - name: ${{ matrix.task.name }}
        run: ${{ matrix.task.command }}
